### ISSUE TITLE
Missing target warning is shown for external links copy pasted into editor

### ISSUE THREAD

**Issue by bharathatt** [fiduswriter/fiduswriter#1019]
When a website url or any external link copy pasted into the editor, these links are shown in red along with "Internal link lost its target" warning.

I think this warning should only be shown to only internal links, we need to add a check if link is internal or external before showing this warning.

![image](https://user-images.githubusercontent.com/47244366/82867311-3db5ae80-9f48-11ea-8bd6-a2d9b8a5c697.png)

**Comment by johanneswilm** [comment]
Fixed in 3.8.14
