### ISSUE TITLE
German Localization ("Spuränderungen")

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1022]
In the German localization, "tracking changes" has (automatically?) been tranlsated to "Spuränderungen" (in djangojs.po). As this features prominently (e. g. in the Share Document-dialogue), I suggest changing it to "Änderungen verfolgen" soon.

**Comment by johanneswilm** [comment]
Hallo @nmueller18, "Spuränderungen" ist das Wort das unter anderem in LibreOffice benutzt wird. Auf jeden Fall war das der Fall als wir die Übersetzung gemacht haben. "Änderungen verfolgen" könnte Probleme machen weil der String so lang ist, aber wir können das mal untersuchen.

**Comment by nmueller18** [comment]
Eine entsprechende Suche bei Google fördert aber m. E. nur automatisch übersetzte Seiten zutage. Bei OpenOffice sieht das Menü auch anders aus (s. Screenshot).
Statt "Schreiben mit Spuränderungen" könnte man z. B. "Schreiben (Änderungen verfolgen)" benutzen, das sind nur vier Zeichen mehr. Oder man nimmt nur "Änderungen verfolgen". Dass damit das Schreiben inbegriffen ist, versteht sich von selbst.

![Bildschirmfoto_Aenderungen](https://user-images.githubusercontent.com/20249289/83632286-4db03c80-a59f-11ea-8a93-68c2bbd6d07e.png)
