### ISSUE TITLE
CSL-issue with book chapters

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1038]
There seems to be an CSL-issue with the rendering of book chapters (German: "Beitrag in Sammelband"). With several styles, entries are rendered incorrectly. E.g.:
Antiquity: editors preceding ", in" is missing, "(ed.)" is placed BEFORE the editors
Journal of Management: editors preceding ". In" is missing, the editors are placed in brackets together with ", Eds.)". This is followed immediately without space by the book title, therefore ", " is missing. 
Journal of Neolithic Archaeology: everything after the paper title is missing.
Other entries are fine.

**Comment by johanneswilm** [comment]
@nmueller18 Have you checked whether this is working in CSL in general? You can check citeproc-plus here: https://fiduswriter.github.io/citeproc-plus/ and for general styles ?

If this doesn't help, what citation style were you using?

**Comment by nmueller18** [comment]
I have checked with Zotero (styles "Antiquity", "Journal of Management", "Journal of Neolithic Archaeology"), and in all cases, the references are rendered as expected. Is there a way with citeproc-plus to specify the references to be rendered? @incollection does not seem to be part of the examples ...
Below is one of the incriminating references, as exported by Zotero in BibTex-style and correctly imported by FidusWriter (but incorrectly rendered):

@incollection{batora_settlement_2014,
	address = {Oxford},
	title = {Settlement {Strategies} in the {Early} {Bronze} {Age} in {South}-{Western} {Slovakia}},
	booktitle = {Settlement, communication and exchange around the {Western} {Carpathians}: {International} {Workshop} held at the {Institute} of {Archaeology}, {Jagiellonian} {University}, {Krakow}, {October} 27–28, 2012},
	publisher = {Archaeopress},
	author = {Bátora, Jozef and Tóth, Peter},
	editor = {Kienlin, Tobias L.},
	year = {2014},
	pages = {325--340}
}

**Comment by johanneswilm** [comment]
The problem seems to be that we translate "incollection" to the very generic "entry" in CSL. You can paste the bibtex here to see what CSL comes out of it: https://fiduswriter.github.io/biblatex-csl-converter/ . I am not sure what the correct translation would be. These is the list of possible types in CSL: https://docs.citationstyles.org/en/1.0.1/specification.html#appendix-iii-types . Maybe you have a suggestion?

**Comment by nmueller18** [comment]
I see your problem. It is strange that CSL does not differentiate between @inbook and @incollection as Bibtex does. In this case I think that the CSL-type "Chapter" would be appropriate, provided that the editor(s) are listed.

**Comment by johanneswilm** [comment]
This should be fixed now in version 3.8.18. Please reopen if you find more similar issues.
