### ISSUE TITLE
wsgi.py file not found

### ISSUE THREAD

**Issue by junoriosity** [fiduswriter/fiduswriter#1040]
I want to deploy fiduswriter with nginx and gunicorn. But for gunicorn I need to have some wsgi.py file, which I cannot find anywhere. Could you provide me with the details of how to make the deployment happen with nginx and gunicorn resp. how to use something along the lines of a wsgi.py file.

**Comment by johanneswilm** [comment]
Hey,
you cannot run it like that as it needs to provide a websocket connection. In the wiki you can see some ways it can be run: https://github.com/fiduswriter/fiduswriter/wiki
