### ISSUE TITLE
Multiple loading of optional sections menu

### ISSUE THREAD

**Issue by anandksalien** [fiduswriter/fiduswriter#1043]
### Duplication of optional section menu

Assume a situation , where in a client is connected to the server , but all the messages the client has sent didn't reach the server. After sometime the server got the newest message that the client had sent and asks for the client to resend all the lost messages. If the client does not have all the messages the server is requesting , it'll ask the server resend the document to start from beginning. At this point , we execute the load_document() function , which leads to multiple entries of optional section in the header bar.

**Sample Image:**

![image](https://user-images.githubusercontent.com/46891412/89031743-b5d98f80-d350-11ea-8391-faa582abc078.png)

**Steps to reproduce:**

Reset the client counter in the front end with a very large number , so that the server would ask client for the lost messages and this in case would lead to reload of the editor using the load_document() call. Leading to the issue of duplication of the headerbar menu item.

**Comment by johanneswilm** [comment]
Fixed in 3.8.18
