### ISSUE TITLE
"Share document" list of access is not dismissed after selecting option

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1055]
It seems that the list of options for "Share document" does not close after one of the option ("Write", "Write tracked" etc.) has been selected (MacOS 10.13.6, tried with Firefox, Chrome, Safari). Is there a deliberate reason for this behaviour? It seems to me much more intuitive to close this window automatically once the user has selected the relevant option.

**Comment by johanneswilm** [comment]
Yes, this is so that you can add/change/remove several access rights at the same time for the same document.
