### ISSUE TITLE
[NODEJS] Entrypoint and Asset size limit

### ISSUE THREAD

**Issue by magic-debian** [fiduswriter/fiduswriter#1079]
Debian Buster - 64bit

Hi all, 

I recently tried to install Fiduswriter on my VPS and everything looked fine during the installation, followed the [Installation and configuration on Ubuntu using snap](https://github.com/fiduswriter/fiduswriter/wiki/Installation-and-configuration-on-Ubuntu-using-snap) 

This is the only error I get during install:
```
> husky@4.2.1 install /var/snap/fiduswriter/593/.transpile/node_modules/mathlive/node_modules/husky
> node husky install

husky > Setting up git hooks
Cannot read property 'toString' of null
husky > Failed to install
```

And also the fact that there are 

```
added 2716 packages from 779 contributors and audited 1504 packages in 93.898s

129 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Bundling MathLive
```

Yet when `sudo /snap/bin/fiduswriter.configure` (my snap/bin is not in $PATH) I get the following warnings:

``` 
 WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
 This can impact web performance.
 Assets: 
   3-1605179657.js (433 KiB)
   16-1605179657.js (344 KiB)
   document_template_admin.js (1.26 MiB)
   21-1605179657.js (622 KiB)
   maintenance.js (248 KiB)
   25-1605179657.js (1.4 MiB)
   26-1605179657.js (649 KiB)
   27-1605179657.js (626 KiB)
   35-1605179657.js (567 KiB)
   36-1605179657.js (337 KiB)
 
 WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). is can impact web performance.
 Entrypoints:
   document_template_admin (1.26 MiB)
       document_template_admin.js
   maintenance (248 KiB)
       maintenance.js 
```

That's just a warning I thought that was no major issue but here is the output on my website (and for the whole website) so no CSS :

![size](https://user-images.githubusercontent.com/64414467/98945734-316fde80-24f3-11eb-9bf6-17ab3d3c508d.png)

and this is my console log: 

![network](https://user-images.githubusercontent.com/64414467/98946693-7f391680-24f4-11eb-87d7-097ac5b14f06.png)

From what I searched I need to [increase my performance](https://webpack.js.org/configuration/performance/) in webpack.js but have close to 0 knowledge in JS so I'm not sure about it.

Apart from my allowed.hosts and the port number (4386) I didn't modified much from the `fiduswriter.configure` file

Thank you for any leads (I should be using the latest and greatest versions of both fidus)

**Comment by johanneswilm** [comment]
The file sizes are just warnings and they are infrequently used files so that is quite OK. What browser is that happening in?

**Comment by johanneswilm** [comment]
Closing as no further info was provided.
