### ISSUE TITLE
unhandledrejection when using invalid passwort reset key

### ISSUE THREAD

**Issue by almereyda** [fiduswriter/fiduswriter#1096]
When trying to recover a password with a password reset link for an account for which another password reset link had been created in the meantime, the key will be invalid and the request goes to `/key//`.

Browser and server report similarily:

```
app_1       |   details: unhandledrejection, JSON.parse: unexpected character at line 1 column 1 of the JSON data                                                      
app_1       |   user: yala
app_1       |ERROR:javascript_error:Got error:
app_1       |   context: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0 
```

There will be no visual response in the UI about the action having failed.

**Comment by johanneswilm** [comment]
@almereyda I cannot reproduce this. If I request two password reset links, both of them work. If I use one, then both are invalidated. If I try to use it anyway, I as the end user receive a clear warning message saying that the key is invalid.

What steps does one need to go through to arrive at this?
