### ISSUE TITLE
Column style in table configuration dialog is not effective

### ISSUE THREAD

**Issue by bharathatt** [fiduswriter/fiduswriter#1098]
There is no change in the table layout when we change the columns style in below table configuration dialog
![image](https://user-images.githubusercontent.com/47244366/102504338-b330ca00-40a6-11eb-8c44-8d76375c476f.png)

Table layout always stays fixed. 
Updating CSS Rules related to table layout in document.css, would fix this.

**Comment by johanneswilm** [comment]
Hey @bharathatt  - could you write a fix for this?
