### ISSUE TITLE
Fiduswriter on another https port and email delivery

### ISSUE THREAD

**Issue by nukedone** [fiduswriter/fiduswriter#1111]
I ran into an issue when I tried to send a recover password email to my account address. Due to the existence of other services I set up my fiduswriter server to run on a non-standard port (9998). However, in recovery email the link does not contain the port that I chose and the protocol is http instead of https. How can I set up the https and port 9998.

Thanks!

**Comment by johanneswilm** [comment]
Hey @nukedone , that's like an interesting issue. Yes, if you are not on port 443, it assumes you are using HTTP because that is the case in 99.99% of cases. 

Let me see what I can do. Is there a particular reason why you did not just use another subdomain for Fidus Writer?

**Comment by nukedone** [comment]
Hey, Johannes,

I used a nonstandard port, because I have plenty of other services on my IP address. I don't know how to make another domain name to bind to the same external IP

⁣Get BlueMail for Android ​

**Comment by johanneswilm** [comment]
Hey,
yes, so usually you would serve several domains or subdomains from the same
server that has just one IP- number. Both Apache and NGINX let you do that.
Are you not using one of those?

**Comment by johanneswilm** [comment]
I will close this issue for now as this usually should not be an issue as there are no limits to number of (sub) domains hosted on the same machine. Please reopen if you still think this is something that needs to be treated.
