### ISSUE TITLE
Drag-and-drop from Zotero broken?

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1124]
Is it possible that the last update broke the drag-and-drop-functionality of references? At least on my system (MacOS 10.13.6, Firefox and Chrome), dragging from Zotero leads to a formatted reference, not the expected place-holder with a full reference at the end of the document.

**Comment by johanneswilm** [comment]
Quick test here and it is still working for me. What instance are you trying on? Is the export format of Zotero configured correctly?

**Comment by nmueller18** [comment]
Of course, it was not! Sorry for the hassle! Reminder to myself: "Always choose BibTeX-Format …"
