### ISSUE TITLE
Cannot create fiduswriter-venv with virtualenv provided in anaconda python 3.4

### ISSUE THREAD

**Issue by kcleung** [fiduswriter/fiduswriter#113]
I am running OS X 10.10.4 with anaconda python 3.4 and brew.

I am now following  README.md  to install fiduswriter-venv.  In step 2, python-dev and python-virtualenv are provided by anaconda python 3.4, and libjpeg and gettext are provided by brew.

Then in step 4, when I run:

virtualenv --no-site-packages fiduswriter-venv

It fails with this message:

abcs-MBP:fiduswriter abc$ virtualenv --no-site-packages fiduswriter-venv
Using base prefix '/Users/abc/anaconda'
New python executable in fiduswriter-venv/bin/python3
Also creating executable in fiduswriter-venv/bin/python
ERROR: The executable fiduswriter-venv/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/Users/abc/git/dev/fiduswriter' (should be '/Users/abc/git/dev/fiduswriter/fiduswriter-venv')
ERROR: virtualenv is not compatible with this system or executable
abcs-MBP:fiduswriter abc$ 

So can you see what's wrong here?

**Comment by johanneswilm** [comment]
That error message is triggered even before you start installing Fidus Writer. It seems like there is something wrong with your installation of python.
