### ISSUE TITLE
Anchors not available as links

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1148]
You can mark arbitrary text as "anchor" by highlighting and clicking on the anchor-symbol on the right.
From my understanding, this anchor should then be available in the "Link"-window under "Cross reference" and (or?) "Internal". However, this is not the case. Is this a bug or do I miss something essential?

**Comment by johanneswilm** [comment]
Good point. Well, I'd call it a missing feature. I'll have to investigate all the export formats, but I am suspecting that there is no good way to do good cross-references in some export formats. I'll look at it and get back to you.

**Comment by johanneswilm** [comment]
Fixed in 3.10.0-rc.1
