### ISSUE TITLE
Close Comment-Popup-Window after submitting comment

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1155]
At the moment, the Comment-Popup-Window stays open when the button "Submit" has been hit. I do not see the reason for this behaviour, and it irritates me again and again that I have to click into the main text to make the window disappear. I would rather prefer that the window closes automatically after hitting the submit-button.
I know that I can also make this happen by clicking "Cancel" but I do not want to cancel my action but to close the comment. Therefore, as a side-note, the "Cancel"-button would be more appropritately called "Close", IMHO (and perhaps change interactively to "Cancel" when the cursor is in the comment-field).

**Comment by johanneswilm** [comment]
Hey @nmueller18 I see what you mean. The problem with taking away the focus from the comment immediately that I can see would be if you have a really long comment and you make a change to the end of it (or add an answer to the comment). After clicking "Submit" you can no longer see the text you added/changed and so some users may want to go back onto the comment to verify that what they wrote is actually there.

But we can try taking away focus from the comment after submitting during one release and then see if we get complaints about that.

**Comment by johanneswilm** [comment]
Fixed in 3.10.0-rc.1
