### ISSUE TITLE
Slash ("/") in title transforms document to folder

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1167]
With the new version of FW 3.10, when a document contains a slash ("/") in the title it is transformed to a folder in the document overview window and can only accessed via the admin-panel. Eliminating the slash there makes the text accessable again.

**Comment by johanneswilm** [comment]
Issue has been reproduced.

**Comment by johanneswilm** [comment]
Fixed in 3.10.1
