### ISSUE TITLE
Latex Export

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1169]
I suggest certain refinements for the Latex Export:
- for proper wrapping of figures I suggest using `\usepackage{wrapfig}`. The code for figures would then be wrapped into
`\begin {wrapfigure}{[variable alignement]}{[variable imgwidth]}
.
.
.
\end{wrapfigure}`
- it seems that the information of the alignement of the figure is not exported properly, BTW. This is probably also better handled by `wrapfig`.
- at least on my system (MacOS 10.13.6), I also need the following two packages for properly formatted Latex: `\usepackage[T1]{fontenc}` and `\usepackage[utf8]{inputenc}`
- also on my system, I need to add this at the first line: `% !TEX TS–program = pdflatexmk`. This certainly depends on the engine used, but it might be useful for others to add this information to the README.

**Comment by johanneswilm** [comment]
Interesting. The exporter was initially aimed at only the most recent incarnation of LaTeX: The LaTeX on the LuaTeX compiler (LuaLaTeX). The reason behind this being that it would be too much work to make it work on other engines. However, it sounds like the pdftex compiler won't disappear and as if it is almost working with our output? In that case, maybe we should try to also target it. What are the reasons why users use pdflatex rather than lualatex these days?

**Comment by nmueller18** [comment]
Ignorance, I suppose. I am using the GUI-app TeXShop, and LuaLatex is one of several options, without any hint that it might be superior to pdflatex.
Indeed, with LuaLatex the FW-export compiles without problems and without the need to set either `fontenc` or `inputenc` or editing the first line. Perhaps add to the Readme: "We strongly advise to use the latest LuaLatex-engine" or similar?
However, the wrapping of figures still does not work correctly and still needs the changes of `wrapfigure` named above.

**Comment by johanneswilm** [comment]
I see. Yes, the readme mentions lualatex but doesn't say that the output is not made for pdflatex. The background being that we thought in 2012 that pdftex would soon disappear and be replaced by luatex as it has built-in support for UTF-8 characters, etc. . I will have to look into what happened there and why pdftex is still around and apparently the default choice in a lot of cases.

I'll also test the `wrapfigure` issue.
