### ISSUE TITLE
Folder names with space are saved with URLEncoded whitespace character

### ISSUE THREAD

**Issue by almereyda** [fiduswriter/fiduswriter#1197]
When entering a document that lies within a directory that contains a space, that character is instead displayed in URLencoded form as `%20`.

![Bildschirmfoto von 2022-03-03 17-29-31](https://user-images.githubusercontent.com/1645308/156608157-b2c2d223-2121-40b9-9190-f889fafa254d.png)

**Comment by johanneswilm** [comment]
@almereyda I couldn't reproduce this. Given a document the exact same name as yours, then exiting and reentering the document have me the name without the urlencoding. Maybe there are other factors? Could you try to find out under which circumstances exactly this happens?
![spaces](https://user-images.githubusercontent.com/595512/156814247-b7c17312-f0b1-4252-b528-f29ed0369eca.png)

**Comment by almereyda** [comment]
Apparently this happened at creation time:

![Bildschirmfoto von 2022-03-07 23-23-26](https://user-images.githubusercontent.com/1645308/157128068-82c85a4e-9310-41dc-b7f1-736ea24eafe2.png)

![Bildschirmfoto von 2022-03-07 23-23-36](https://user-images.githubusercontent.com/1645308/157128085-65d814a2-ac84-4e96-9e6d-5d7a525505cf.png)

At least now it's become permanent.

These artefacts were not there when initially creating the "folder" and entering it, prior creation of said document.

---

The replication goes like this:

![Bildschirmfoto von 2022-03-07 23-25-36](https://user-images.githubusercontent.com/1645308/157129443-4a2332eb-c4b9-49cf-8519-6162743ae7e2.png)

![Bildschirmfoto von 2022-03-07 23-25-07](https://user-images.githubusercontent.com/1645308/157129445-6bea1c58-eb36-4d4a-96f6-588af9dbf706.png)

![Bildschirmfoto von 2022-03-07 23-25-18](https://user-images.githubusercontent.com/1645308/157129438-88df118b-0d62-4465-9f45-6e1024f23380.png)

---

![Screenshot 2022-03-07 at 23-26-43 Dokumentenübersicht - Fidus Writer](https://user-images.githubusercontent.com/1645308/157128707-e26e7ac5-9d88-4cd2-a5db-ded272e0a889.png)

![Bildschirmfoto von 2022-03-07 23-27-34](https://user-images.githubusercontent.com/1645308/157128705-d144a593-e68a-4e77-a790-4a4aac42fc28.png)

![Bildschirmfoto von 2022-03-07 23-27-45](https://user-images.githubusercontent.com/1645308/157128702-c9b9b7cc-3d06-406b-af75-b2fca84c819e.png)

![Bildschirmfoto von 2022-03-07 23-28-09](https://user-images.githubusercontent.com/1645308/157128695-7e7fa3d3-b1e6-4808-957b-5cab37aec2f0.png)

![Bildschirmfoto von 2022-03-07 23-28-23](https://user-images.githubusercontent.com/1645308/157128692-95caffa5-6bbd-4f44-ae9f-26ceffc42482.png)

---

![Bildschirmfoto von 2022-03-07 23-30-47](https://user-images.githubusercontent.com/1645308/157129221-d92e700b-e4a4-40d5-806a-a75e733dd73a.png)

![Bildschirmfoto von 2022-03-07 23-31-00](https://user-images.githubusercontent.com/1645308/157129218-4b172d5a-1103-49c3-a88b-5ba446a0cd93.png)

![Bildschirmfoto von 2022-03-07 23-32-46](https://user-images.githubusercontent.com/1645308/157129215-f80fe32d-f8dc-4f48-b9ba-908d26a674c2.png)

**Comment by almereyda** [comment]
Interestingly, it was possible to rename-recreate a new folder that contained a correct white space character, by replacing the `%20` with a space when editing the document title.

Looking forward to the `v3.10.18` release through #1198 to test the fix.

**Comment by johanneswilm** [comment]
@almereyda  This issue should be fixed in version 3.10.18 which was released today. 

Please reopen this ticket if it turns out that the issue has not been resolved fully.
