### ISSUE TITLE
German localisation: Use "Passwort" throughout

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1242]
In some instances, the English term "Password" is translated with "Kennwort", in others with "Passwort". In the registration dialog, this is even mixed (see screenshot). I suggest to use "Passwort" throughout which seems to me more common usage.

![Passwortdialog](https://user-images.githubusercontent.com/20249289/222137391-8692effc-6064-4239-a7d3-b41451db354d.jpg)

**Comment by johanneswilm** [comment]
Done in https://github.com/fiduswriter/fiduswriter/commit/e24e6f3422d7ff6f1d69e3967eeb9d08db3104c0
