### ISSUE TITLE
Unhandled rejection while exporting docx/odt

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1243]
Perhaps connected to the new version of the docx/odt-export-plugin, there is an error when trying to export a larger document as docx/odt-file. This does not happen with other exporters (html, Fiduswriter) or with a shorter document.
The error code for Firefox is as follows:

```
Report at /api/django_js_error_hook/
Got error: 
	context: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
	details: unhandledrejection, An invalid or illegal string was specified, parRender@https://####/static/js/6004-1679828516.js:32:8279
6004/render/<@https://####/static/js/6004-1679828516.js:32:7580
render@https://#####/static/js/6004-1679828516.js:32:7535
6004/init/<@https://####/static/js/6004-1679828516.js:380:1923

```

For Chrome and Safari, the code is slightly different:

```
Got error: 
	context: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
	details: unhandledrejection, Failed to execute 'insertAdjacentHTML' on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document., Error: Failed to execute 'insertAdjacentHTML' on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
   at x.parRender (https://###/static/js/6004-1679828516.js?__WB_REVISION__=a0a4d4ed23f225b5398d1cf9fa5f6ff0:32:8279)
   at https://###/static/js/6004-1679828516.js?__WB_REVISION__=a0a4d4ed23f225b5398d1cf9fa5f6ff0:32:7580
   at Array.forEach (<anonymous>)
   at x.render (https://###/static/js/6004-1679828516.js?__WB_REVISION__=a0a4d4ed23f225b5398d1cf9fa5f6ff0:32:7535)
   at https://###/static/js/6004-1679828516.js?__WB_REVISION__=a0a4d4ed23f225b5398d1cf9fa5f6ff0:380:1923
```
This happens on macOS 12.6.3 on Chrome, Safari and Firefox.

**Comment by johanneswilm** [comment]
@nmueller18: This looks like it is an error specific to certain content that it tries to render. If it is possible, it would be good if you could provide a minimum example fidus file that shows this behavior. For example, you could make a copy of the file and in the copy try to first remove the first half of the contents and then the second half to see which half causes the error and of the remaining file again try to remove first one half, and then the other half until you have a sufficiently small file that you can share. That would be helpful.

**Comment by nmueller18** [comment]
Thanks for the suggestion!
That way, I found the culprit surprisingly fast: It is a non-printing sign, obviously remnants of a reference manager as it appears before and after references. I can see and remove the sign in an editor like BBEdit (there, it appears as `\x{08}`) but the browsers are not able to find it. In the admin panel, the sign appears in the Contents/Diffs fields as `\b`.

Is it save to copy the text in either (or both?) fields, edit it in BBEdit and paste it back again?

**Comment by johanneswilm** [comment]
If the file isn't opened in Fidus Writer, you can open it in the admin interface and copy-paste the json from there. And that is safe, yes. We probably should add a scan for that character. `\b` is probably a backspace character. Not sure about `\x{08}`. Was it introduced by means of pasting? If yes, it may be enough to filter it out during paste.

**Comment by nmueller18** [comment]
Yes, the text and the non-printing character was added by pasting. I am not sure what side-effects filtering during import could have. Perhaps it would be enough to filter those characters when _exporting_ to docx-/odt-files. At least an explicit error message would be helpful.
BBEdit has a function aptly called `Zap Gremlins` which deletes Non-ASCII characters, Control characters and Null (ASCII 0) characters (including the incriminating `\b`). Something like that in the Tools-section of FW might also be handy.

**Comment by johanneswilm** [comment]
There should be no side effects deleting these during paste. We do clean up several other things during paste, but had not filtered for this particular character in the past. We cannot really delete all non-Ascii-characters, as that will also mean that characters such as ö, ä, and ü would be deleted
