### ISSUE TITLE
webpack using high CPU, mysql & fiduswriting restarting

### ISSUE THREAD

**Issue by klausru** [fiduswriter/fiduswriter#1244]
Dear all, dear @johanneswilm 
with the latest version 3.11.13 of fiduswriter `webpack` is using very high cpu loads. Along with that `java` uses high cpu loads, and `mysqld`, and fiduswriter are contantly restarting.
The system is Ubuntu 22 LTS headless server.
This [ticket](https://github.com/webpack/webpack-dev-server/issues/1180) says that `fsevents` should be present, but what I saw during / after configuring fiduswriter is that `fsevents` was uninstalled. `fsevents` is currently optional but it should be marked as dependent.
What could I quickly do to solve this?
Can someone replicate or confirm this?

Thanks for your help

**Comment by johanneswilm** [comment]
Hey @klausru ,
is this a problem that only happened with version 3.11.13 and no previous versions? Did you install it using the snap or in some other way?

Let me investigate about fsevents.

**Comment by klausru** [comment]
Dear @johanneswilm 
yes, the versions before ran fine. I installed via snap

**Comment by johanneswilm** [comment]
Hey again @klausru ,
Are we talking about this package: https://www.npmjs.com/package/fsevents ? That seems to be Mac OS specific.

Webpack should only run after doing any change in the configuration for up to a few minutes. After that, it should not run. The java application and the MySQL server are all independent executables. So I'm wondering - maybe you are hitting resource limits (RAM, CPU or harddisk space?) that kill those processes and then make them run again. Is that a possibility?

I will look at anything that changed in version 3.11.13 next.

**Comment by johanneswilm** [comment]
@klausru The changes between 3.11.11 and 3.11.13 should all just be in the frontend code (code that is running in the browser), so it doesn't look like any of that caused the performance issues you mentioned.

**Comment by johanneswilm** [comment]
fiduswriter.com is also running the latest snap, and I cannot see anything like that. However, for version 3.10.x, the amount of the VPN it runs on was exchanged for one with a higher amount of RAM.

**Comment by klausru** [comment]
It seems that it was necessary to free up and increase RAM memory. 
All fine for now, thanks
