### ISSUE TITLE
DATA_UPLOAD_MAX_MEMORY_SIZE

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1246]
Editing a medium-sized document in the admin-panel (`…/admin/document/document/`) leads to the error-message `Bad Request (400)`, and the back-end reports `Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.`

According to the [Django-documentation](https://docs.djangoproject.com/en/4.2/ref/settings/#data-upload-max-memory-size), this is related to the setting of the maximum upload size which by default is 2.5 MB. Unfortunately, in the admin-panel there is no obvious way to adjust this setting.

Two obvious solutions would be to either expose this setting to the user or choose a higher value by default.

**Comment by johanneswilm** [comment]
Hey @nmueller18 ,
these settings are exposed and can be adjusted by the person who has access to your server. It's the same file in which the plugins are enabled, the mail settings set, etc. .

**Comment by nmueller18** [comment]
This did the trick, thank you!
May I suggest to add this to the documentation and the string to the setting file?
