### ISSUE TITLE
Saving revision fails

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1265]
Saving revisions tends to fail with long documents containing many images, tables, corrections and comments with the not very helpful message `Revision could not be saved`. I wonder if there is a log which could explain what is happening or if it is simply a timeout error?

**Comment by johanneswilm** [comment]
If this is in large documents, my guess is that the total size of the document is larger than the max upload size of files to the server as the revision will be one large file. 
In configuration set it to the number of bytes like this:

1. Enter configuration `sudo fiduswriter.configure`

2. Add these settings:

> DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 50  # 50MB, default is 2.5MB
> FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE


If you are running behind NGINX, it could also have such a setting. The setting name there is `client_max_body_size`.

**Comment by johanneswilm** [comment]
While you are in the configuration, you can also configure where and if error messages are logged. The logging setup is quite complex. Look for "Django logging setup" to see all the options. The default is that an email is sent to the administrator for every error (frontend and backend).

**Comment by nmueller18** [comment]
> If this is in large documents, my guess is that the total size of the document is larger than the max upload size of files to the server as the revision will be one large file. In configuration set it to the number of bytes like this:
> 
> 1. Enter configuration `sudo fiduswriter.configure`
> 2. Add these settings:
> 
> > DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 50  # 50MB, default is 2.5MB
> > FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE
> 
> If you are running behind NGINX, it could also have such a setting. The setting name there is `client_max_body_size`.

Thank you for the quick response! However, this does not seem to be at the heart of the problem. I can download the respective file and upload it again without problems.
I usually receive lots of error messages but none related to the problem of saving revisions.

**Comment by johanneswilm** [comment]
When you download the file through the fidus writer user facing interface, the file is assembled in the browser and therefore doesn't touch the server. When you upload it, it is being dissassembled in the browser before being uploaded to the server and therefore will not hit the server limits either. It is only when a revision is create and saved that the file is assembled in the browser and then uploaded to the server, at which stage the limits may be hit.

If you download/upload through the admin interface, then this does not happen. So if you are able to upload the file through the admin interface, then there is indeed no file size limit issue.

**Comment by nmueller18** [comment]
Ah, I did not realize how the upload process works. Where do I upload files via the admin interface? I cannot find this option.

**Comment by johanneswilm** [comment]
@nmueller18 You can try to upload one at this URL for some random document. /admin/document/documentrevision/add/

**Comment by nmueller18** [comment]
Thanks for the hint, and you were right. The upload fails with the message `413 Request Entity Too Large - nginx/1.18.0 (Ubuntu)`. So, the error really seems to be related not to the fiduswriter server but with nginx.

**Comment by nmueller18** [comment]
I think the thread can be closed now but perhaps it is possible to give more helpful feedback so the user knows where the problem is and how to remedy it (replace images with smaller ones)?

**Comment by johanneswilm** [comment]
Good point. The question is how much information the server operator wants the end users to see. I'll think about that.

As for NGINX - I hope you fixed it using the `client_max_body_size` setting in the NGINX configuration.

**Comment by nmueller18** [comment]
Actually, a technician solved the problem for me when the setting in the `nginx.conf` file did not seem to have any effect. It turned out that there was another setting file `/sites-available/fidus` which overrode the general setting. Now revisions of larger files can be saved as expected.
