### ISSUE TITLE
theEditor.editor is undefined

### ISSUE THREAD

**Issue by titusstahl** [fiduswriter/fiduswriter#129]
While trying to export or add comments, I regularly get the following error:

`details: http://.../static/js/c7d9d2f5caab.js:1653: TypeError: theEditor.editor is undefined
	context: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
`

This is on 0ceb81ba67d4384208bb8acacb4007e17c6cb87e

Thanks!

**Comment by johanneswilm** [comment]
Could you say a little about what you are doing just prior to that, what contents the document has and how you are trying to export (where do you click)?

**Comment by johanneswilm** [comment]
Also, it looks like you have debugging disabled. It would help a lot if you could enable it so that I can see what line that is referring to.

**Comment by titusstahl** [comment]
I have an untitled document with a h1 header and one paragraph of text. I log in, open the document, click "Export-LaTeX" or the comment button (error appears in both cases).

This is the debug output

```
Websocket opened
get_document
participant_update
ERROR:javascript_error:Got error: 
	details: http://myaddress.onion:8000/static/js/editor/comment-helpers.js:327: TypeError: theEditor.editor is undefined
	context: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
	user: xxxxx
ERROR:javascript_error:Got error: 
	details: http://myaddress.onion:8000/static/js/editor/editor.js:103: TypeError: theEditor.comments is undefined
	context: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
	user: xxxxx
```

In the Firefox console, I get the following errors

```
12:34:51.938 TypeError: result is null
receive/maps<() editor.js:1744
map() self-hosted:235
receive() editor.js:1742
[1]</theEditor.applyDiffs() editor.js:144
[1]</theEditor.initiate() editor.js:66
<anonym> setup.js:375
usermediaHelpers.getImageDB/<.success() usermedia-helpers.js:530
jQuery.Callbacks/fire() jquery-2.0.3.js:2913
jQuery.Callbacks/self.fireWith() jquery-2.0.3.js:3025
done() jquery-2.0.3.js:7400
.send/callback/<() jquery-2.0.3.js:7822
logError() utils.js:36
window.onerror() utils.js:40
1 editor.js:1744:9

12:34:52.209 TypeError: theEditor.editor is undefined
commentHelpers.layoutComments() comment-helpers.js:327
editorHelpers.displaySetting.documentstyle/set_document_style_timer<() setup.js:198
1 comment-helpers.js:327:9

12:34:57.343 TypeError: theEditor.comments is undefined
[1]</theEditor.getUpdates() editor.js:103
<anonym> setup.js:442
jQuery.event.dispatch() jquery-2.0.3.js:4675
jQuery.event.add/elemData.handle() jquery-2.0.3.js:4360
1 editor.js:103:5
```

**Comment by johanneswilm** [comment]
I have tried to reproduce this and failed. I created a new document, didn't give it a name, but types one H1 line in the body, and then another paragraph beneath it (see attached fidus doc). I then export it to LaTeX. It works. I then log out and in again and enter the editor and try to export it as LaTeX, and it works. 

Any other step? Are you on the newest version of the 3.0 branch, or could it be that you have an older version installed? Please update to the latest commit of the 3.0 branch.

[untitled-document.zip](https://github.com/fiduswriter/fiduswriter/files/102303/untitled-document.zip)

**Comment by titusstahl** [comment]
With the latest changes, it works! Thank you so much!
