### ISSUE TITLE
On fresh install (github master), TypeError: theDocument is undefined

### ISSUE THREAD

**Issue by zeigerpuppy** [fiduswriter/fiduswriter#133]
I have installed fiduswriter from github today on a Debian Wheezy server
using the default installation in structions.
I can log in but when I try to create a new document, I have this error in the console:

``
ERROR:javascript_error:Got error:
        details: https://server.fqdn/static/js/editor/editor.js:132: TypeError: theDocument is undefined
        context: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:44.0) Gecko/20100101 Firefox/44.0
        user: Obfuscated
``
Chrome and Safari give the same errors
I have included a snapshot of the page here too
![2016-02-05 02 32 24 pm](https://cloud.githubusercontent.com/assets/415981/12837301/5a3cb18a-cc15-11e5-9b95-9165819c24e2.png)

**Comment by johanneswilm** [comment]
@zeigerpuppy Have you tried installing on Ubuntu? We have installed on multiple servers lately, and it works everywhere. Debian XY is not officially supported. If this is the reason you rejected the claim that it now works on Firefox, that is not OK. It does work on Firefox. What you are asking for is a new feature: Debian XY support/install instructions.

**Comment by johanneswilm** [comment]
Same goes for realtime support.

**Comment by zeigerpuppy** [comment]
Considering I am paying the bulk of the bounties, I would like to test the support for the new features.
Fiduswriter used to work on debian so i'm a little surprised support is now broken.
I would at least appreciate some suggestions as to what the problem may be, especially considering must of the Ubuntu libraries should be very similar to Debian.
Is this likely to be a dependency issue or a python version issue?  The install procedure had no errors.

**Comment by johanneswilm** [comment]
Sorry, until you give up your rejection, there will be nothing from our side on your debian issue. The bounty does not exactly pay for the thousands of programming hours. If it's never being paid - fine. But I am not about to start working on a ton of other bugs to get the bounty posted for something else.

**Comment by zeigerpuppy** [comment]
Do you have a test install where I can try out the new features?

**Comment by johanneswilm** [comment]
@zeigerpuppy Check your email inbox. Note that this is special service that is *not* required in terms of the bountysource claim.

**Comment by zeigerpuppy** [comment]
I have finally had the time to install a fresh fiduswriter on an Ubuntu 14.04 machine
However I get the same error, non functional in chrome, safari and firefox

```
ERROR:tornado.general:Could not open static file None
ERROR:javascript_error:Got error:
        details: https://fidus.greenant.net/static/js/editor.es5.js:32866: RangeError: Index 1 out of range for <paragraph>
        context: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2
```

**Comment by johanneswilm** [comment]
Have you followed the install instructions in every detail, or have added you own customizations? I stallations have been performed by at least 10 people independently, and none other than you have encoubtered this.

**Comment by zeigerpuppy** [comment]
I followed the instructions exactly as in the "Simple Install" docs and then put the site behind two different types of proxies to check if that was the issue (as it is running on a headless server):

Here are the proxy settings used (I've left out the irrelevant bits)
nginx:
```
  location /fidus/ {
    rewrite ^/fidus/(.*)$ /$1 break;
    proxy_pass http://server:8000;
    proxy_redirect http://server:8000/ $scheme://$host/fidus/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_read_timeout 20d;
  }
```

apache proxy
```
        ProxyPass / http://server.castellum:8000/
        ProxyPassReverse / http://server.castellum:8000/
```

I also noticed this failure during build, maybe it's the cause?:
```
prebuild WARN install Prebuilt binaries for node version v6.1.0 are not available
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
gyp: Call to 'pkg-config fuse --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
prebuild ERR! configure error
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (/home/zp/Downloads/fiduswriter/node_modules/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
prebuild ERR! not ok
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (/home/zp/Downloads/fiduswriter/node_modules/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
npm WARN install:fuse-bindings@2.8.1 fuse-bindings@2.8.1 install: `prebuild --install`
npm WARN install:fuse-bindings@2.8.1 Exit status 2
```

**Comment by johanneswilm** [comment]
Looking at your error message, this is not the same error message as last time. Can you please open anew issue for this if you don't have any customizations?

**Comment by zeigerpuppy** [comment]
ok will do

**Comment by johanneswilm** [comment]
Don't put the site behind any proxy.

**Comment by zeigerpuppy** [comment]
OK, it is working when not behind a proxy. 
Are there any instructions of how to proxy it properly?
