### ISSUE TITLE
Integration with user defined latex templates

### ISSUE THREAD

**Issue by zeigerpuppy** [fiduswriter/fiduswriter#16]
It would be great to have define more styles with definitions sourced from a template.  For example the Classic Thesis template (http://www.latextemplates.com/template/classicthesis-typographic-thesis) has extra styles including Chapter, Section, etc.
This would make it easier to export from fidus writer to LaTeX (or LyX) for final composition.  Workflow could then be: write chapter -> share for edits on fidus -> export back to LyX as child document

A method like that used by sharelatex.com would be good

**Comment by johanneswilm** [comment]
I don't see any feasible way to do this. See #873
