### ISSUE TITLE
ImportError: No module named django.core.management

### ISSUE THREAD

**Issue by zopyx** [fiduswriter/fiduswriter#172]
Python 2.7, installed Fidus 3.0b1 using pip install -r requirements.txt, reproducible on two systems:

Suxmac-2:fiduswriter ajung$ ./manage.py init
Traceback (most recent call last):
  File "./manage.py", line 26, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

**Comment by zopyx** [comment]
Oh, well, Django specific issue.

bin/python manage.py init

works if you don't use bin/activate like bin

**Comment by johanneswilm** [comment]
:)
