### ISSUE TITLE
Import BibTex Library button throws error: Can't find variable: BibLatexImporter

### ISSUE THREAD

**Issue by zeigerpuppy** [fiduswriter/fiduswriter#176]
Firefox:
```
ERROR:javascript_error:Got error:
        details: http://server:8000/static/js/6cb7c1df690f.js:780: ReferenceError: BibLatexImporter is not defined
        context: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.3.0
        user: xx
```
Safari:
```
ERROR:javascript_error:Got error:
        details: http://server:8080/static/js/6cb7c1df690f.js:780: ReferenceError: Can't find variable: BibLatexImporter
        context: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2
        user: xx
``

**Comment by johanneswilm** [comment]
@zeigerpuppy Thanks. This should be fixed now.

**Comment by zeigerpuppy** [comment]
Still looks to be happening for me, I think I ran the update correctly, the procedure I used was:

```
(venv)$ git pull origin
(venv)$ ./manage.py transpile
(venv)$ ./manage.py migrate
(venv)$ ./manage.py runserver
```

Error appears the same as before:

```
ERROR:javascript_error:Got error:
        details: http://server:8080/static/js/6cb7c1df690f.js:780: ReferenceError: BibLatexImporter is not defined
```

**Comment by johanneswilm** [comment]
You are You probably also need to run ./manage.py collectstatic. I added this to the instructions.

**Comment by zeigerpuppy** [comment]
working now, thanks,

on bibliographies, it would be great if there was an option to paste in bibtex,
that way, integrating with zotero would be easy, just copy and paste if export is set to bibtex format in zotero.

**Comment by johanneswilm** [comment]
@zeigerpuppy: Could youmake a new ticket for that? It will be classified as a feature. Better integration with zotero would be good. I am currently running the firefox-based zotero, and it doesn't seem all that easy to get it to export to the clipboard.

**Comment by zeigerpuppy** [comment]
set the default output format in Zotero to BibTex and the clipbpard is autoformatted
(copy is ctrl-option=c or command-option-c)
![2016-05-14 01 14 49 am](https://cloud.githubusercontent.com/assets/415981/15252491/7b2677ba-1971-11e6-9919-aeb7ac494a57.png)

**Comment by johanneswilm** [comment]
I figured it out. But it took me about 15-20 minutes to find a way to easily install zotero standalone on Linux and set the export to bibtex. Even then it wasn't exactly intuitive that I needed to hit CTRL+Shift+V instead of just CTRL+V to copy items.

I can see how we can make this usable, but it is unfortunate that Zotero is so "cryptic" in how it works. I can see how we will need a video tutorial + description for Windows/Linux/Mac to get people to use this correctly. Nevertheless, could be a feature for version 3.1.

**Comment by zeigerpuppy** [comment]
Yes, it is a bit tricky to do,
I find the plugin better than the standalone zotero (but it only works in firefox).
Zotero could definitely do with an install/usage video too, but it's so good when it does get working (especially because it automatically redirects to University library proxies too)
