### ISSUE TITLE
Feature Request: Prospective sharing

### ISSUE THREAD

**Issue by zeigerpuppy** [fiduswriter/fiduswriter#196]
Currently if a user wants to share a document with a new user, they need to:
1) send a join fiduswriter invite
2) wait for the new user to sign up
3) go back to share dialogue to share doc.

It would be much better if the shared document was queued prospectively for sharing, so the process would be:
1) send a sharing invite for a document
2) when the new user signs up they see the document as shared automatically

**Comment by johanneswilm** [comment]
Indeed, this would be nicer. The only reason why this isn't the case currently is that this makes it all a bit more complex and therefore requires extra programming. If someone wants to program this, it would be among the first things I would add.
