### ISSUE TITLE
firefox support [$100]

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/fiduswriter#20]
There are a number of issues:

* Showing individual pages in the editor is done by using CSS Regions. Firefox has nothing that correponds to it. This is only a minor issue, as the editor can work in a CSS regionless environment.

* Moving the caret/cursor correctly is quite broken in both Firefox and Chrome. A bug has been filed to both of them (Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=873883 Chrome: https://code.google.com/p/chromium/issues/detail?id=242110 ), but so far it does not look promising. Instead, it has been resolved with javascript that intrcepts all key strokes on Chrome here : https://github.com/fiduswriter/fiduswriter/blob/master/text/static/js/movecursor.js This needs to be work on to provide support for Firefox.

**Comment by goranpavlovic** [comment]
Hi, 
I am continue working on key events firefox. 
I am trying to solve this. I am trying to control caret position before and after element removal and control carret position. I am also trying to modify behavior on removal with DOMNodeRemoved and DOMSubtreeModified.Now trying to solve svg/canvas moving.

**Comment by johanneswilm** [comment]
This issue is being solved with the 3.0 branch -- which now supports FIrefox and Microsoft Edge due to the swithc the prosemirror.
