### ISSUE TITLE
Installation On Shared Hosting 

### ISSUE THREAD

**Issue by UdoKifferbrehl** [fiduswriter/fiduswriter#213]
Hi there, 
do you have a zip package which I can upload to my shared hosting (no root privileges)? E.g. like setting up WordPress or Piwik. Thank you very much.

**Comment by johanneswilm** [comment]
Under "releases" you can find zip files [1]. However, Fidus Writer is not just a simple Wordpress/Piwik type webapp. It's a highly complex realtime collaborative editor. So it requires your server to have corresponding capabilities (Python websockets). While root isn't strictly needed, I haven't been able to find a shared hosting provider that provides these capabilities.


[1] https://github.com/fiduswriter/fiduswriter/releases
