### ISSUE TITLE
importing fidus document

### ISSUE THREAD

**Issue by momenifi** [fiduswriter/fiduswriter#260]
I want to upload a fidus document. But if I click on 'select a file', nothing will happen and I cann't select a file.

**Comment by johanneswilm** [comment]
@momenifi This is in FidusWriter 3.0.1, correct? I tried it, and it works fine here on Chrome 51.0.2704.106 (64-bit)/Linux. Which browser and OS are you using?

**Comment by momenifi** [comment]
Right. The problem was browser. I tested it with chrome and works fine.

**Comment by johanneswilm** [comment]
Aha. Which browser didn't work?

**Comment by momenifi** [comment]
firefox

**Comment by johanneswilm** [comment]
This has now been fixed in both 3.0 and 3.1 branches. Released 3.0.2
