### ISSUE TITLE
Use of escape character for LaTex export

### ISSUE THREAD

**Issue by stonfute** [fiduswriter/fiduswriter#263]
Just asimple example:
 If I want to export to latex a text with "&" character inside. When i try to compile latex i get an error ! 
I've to replace manually "&" by "\\&" !

So if it's possible to take care of such character by adding escape character,  it would be nice !

**Comment by johanneswilm** [comment]
@stonfute 

The latex export filter is supposed to create output to be processed with lualatex. This restriction is one of many imposed to keep the export filter as simple as possible. But we need to escape all the characters that need it. So far we do this with these ten: ```& % $ # _ { } ~ ^ \```.

I saw some places it mentioned that ```¿``` should be escaped as well, but my testing indicates that this is not required. Any other characters, @stonfute ?

**Comment by stonfute** [comment]
yeah ! it seems fine, I don't really use any other characters.

**Comment by johanneswilm** [comment]
ok. Closing for now. We can reopen if we find more.
