### ISSUE TITLE
Ability to manage figure's label and inserting reference to them

### ISSUE THREAD

**Issue by stonfute** [fiduswriter/fiduswriter#270]
The ability to manage label of figures (not caption) and make reference to them in text would be a nice feature. 
[http://alvinalexander.com/blog/post/latex/reference-figure-or-table-within-latex-document](http://alvinalexander.com/blog/post/latex/reference-figure-or-table-within-latex-document)

**Comment by johanneswilm** [comment]
Absolutely. Important feature, @stonfute . I saw this on the development map of OSCOSS at one stage. Is it still there, @momenifi ?

**Comment by johanneswilm** [comment]
Available sine at least 3.9,
