### ISSUE TITLE
editor.es5.js Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by stonfute** [fiduswriter/fiduswriter#271]
I just have a that error when i try to export my report to LaTeX.

I use a lot of \alpha, \beta, \gamma in my equations. I think it comes from those equations.

`editor.es5.js Uncaught TypeError: Cannot read property 'replace' of undefined`

the problem seems to be on that line :

`equation = equation.replace(/\\/g, "*BACKSLASH*").replace(/\*BACKSLASH\*\*BACKSLASH\*/g, "\\").replace(/\*BACKSLASH\*/g, "");
`

**Comment by johanneswilm** [comment]
That line was removed in the last fix, which was only applied to the 3.1 branch. The reason for that was that the fix was fairly complex and I didn't want to ibtroduce new sources of errors. But if you promise to test this extensively, maybe we should try.

**Comment by stonfute** [comment]
Ok no problem ! I will update !
