### ISSUE TITLE
jQuery(this).find('figcaption')[0] seems to be undefined

### ISSUE THREAD

**Issue by stonfute** [fiduswriter/fiduswriter#272]
I've switched to 3.1 branch (i've done transpile and collectstatic). When i tried to export my document in latex, it doesn't work !

> Cannot read property 'lastChild' of undefined (chrome)
or 
>  TypeError: jQuery(...).find(...)[0] is undefined (firefox)

When i've tried debug, it seems that innerHTML of 'jQuery(this).find('figcaption')' is empty

`caption = jQuery(this).find('figcaption')[0].lastChild.innerHTML`

I've done some tests, but i don't understand why i've got that error, because my html structure is fine and js should work.

``` html
<figure data-image="7" data-figure-category="figure" data-caption="xx" pm-offset="4567" pm-size="1" class="ProseMirror-selectednode">
<div><img src="/media/images/4fd0b61c-fca7-4a69-87ac-0b83ae97e8e3.jpg"></div>
<figcaption>
<span class="figure-cat-figure" data-figure-category="figure">figure</span><span data-caption="xx">xx</span>
</figcaption>
</figure>
```

it seems to be the same with
`filename = jQuery(this).find('img').attr('data-src')`

It seems that `jQuery(htmlCode).find('figure').innerHTML` is empty

**Comment by johanneswilm** [comment]
Did this work under 3.0? Could you share a test document with me?

**Comment by stonfute** [comment]
Yes, the document was created under 3.0, but it seems to be the same with a new document created under 3.1.
I've done a `git pull` to update and changed branch to 3.1.
I've done `./manage.py init` to reload static files.

I can't share with you the document that was created under 3.0 (confidential) but i can share the one that i've created under 3.1
[fdgdfg.zip](https://github.com/fiduswriter/fiduswriter/files/435118/fdgdfg.zip)

**Comment by johanneswilm** [comment]
looking at it now

**Comment by johanneswilm** [comment]
@stonfute This should fix it.
