### ISSUE TITLE
Curious how server is implemented

### ISSUE THREAD

**Issue by leandermelms** [fiduswriter/fiduswriter#287]
Hi, 
I've been struggling lately with implementing the collab backend of prosemirror in Swift and was wondering how you handle the server talking to prosemirror. I really don't want to rewrite the prosemirror model as it is just a fun project I'm working on in my free time.

Could you briefly explain what challanges you faced creating fiduswriter with prosemirror as text editor? Are you using both Node.js and Python as server languages?

Any hints towards your implementation design would be greatly appreciated.

**Comment by johanneswilm** [comment]
Hey, 
we are using Tornado/Django on the backend. You are welcome to contract me to help you or read through our commented source code  for free. Another option may be to contact the Prosemirror developer directly.
