### ISSUE TITLE
 ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by stonfute** [fiduswriter/fiduswriter#320]
I've tried to update to the last release (git pull + init to collect statics)

When i try to load a page i've an error :

`ERROR:tornado.general:Could not open static file None`
`ERROR:javascript_error:Got error:
        details: https://xxxxxx/static/js/document-overview.es5.js:1533: ReferenceError: jQuery is not defined`

The same with images-overview.es5.js, feedback, bibliography, ...
Is it a missing dependency of jQuery ?

**Comment by johanneswilm** [comment]
How much of the normal installation procedure did you follow? Travis builds
and downloads everything from scratch every time, so a missing jQuery
dependency should show up.
Also: if you have created a configuration.py file earlier, you may need to
update it. For that, look at the default file.

**Comment by psuet** [comment]
I have the same problem.  I installed my installation from ground up and on every page I get this error!

The problem looks to a missig JQuery

**Comment by johanneswilm** [comment]
Jquery should be installed through npm. You are on ubuntu using bash, right? What ubuntu version?

**Comment by psuet** [comment]
I have Ubuntu 16.04 LTS and got this message while ./manage.py init 

`Installing dependencies
npm WARN lifecycle fidus-writer@3.1.0-dev~install: cannot run in wd %s %s (wd=%s                                                                                                                                                             ) fidus-writer@3.1.0-dev napa /fiduswriter
npm WARN lifecycle fidus-writer@3.1.0-dev~postinstall: cannot run in wd %s %s (w                                                                                                                                                             d=%s) fidus-writer@3.1.0-dev npm run get_mml2omml && npm run copy_jquery && npm                                                                                                                                                              run copy_jquery-ui && npm run copy_underscore && npm run copy_datatables && npm                                                                                                                                                              run copy_dropkickjs && npm run copy_dropkickjs_css && npm run copy_citeproc /fid                                                                                                                                                             uswriter
fidus-writer@3.1.0-dev /fiduswriter
+-- babel-preset-es2015@6.16.0
...
`

**Comment by johanneswilm** [comment]
@psuet Are you running this as sudo?

**Comment by johanneswilm** [comment]
@stonfute Are you sudoing?

**Comment by stonfute** [comment]
Runing as root

**Comment by johanneswilm** [comment]
Aha, that's the problem. Only do those things as root where it is specified that you should use sudo or root. Everything else cannot be done as root unless you figure out how to get around npm's restrictions on root/sudo.

@psuet Are you in the same situation?

**Comment by psuet** [comment]
Hey, I was root, because why not ;) I will test it. Thanks for the perfect support!

**Comment by johanneswilm** [comment]
Ok. Good luck!

**Comment by dalareo** [comment]
Still get the same error executing app as normal user, not root

```
Uncaught ReferenceError: jQuery is not defined
```

**Comment by johanneswilm** [comment]
The previous cases were all due to users not following the install instructions fully. Most likely this is the case also this time. If you find out what makes it work on arch linux/docker, please contribute to the wiki.

**Comment by dalareo** [comment]
If I knew when in the installation is the static/js folder populated maybe I could find the reason it is not working inside docker container. It seems js folder does not exist or it is not assigned properly.

**Comment by johanneswilm** [comment]
take a look at ./manage.py init and ./manage.py transpile.

**Comment by dalareo** [comment]
Setting --unsafe-perm option at 'npm install' command it transpile.py lets npm be executed as root

**Comment by johanneswilm** [comment]
Why would you execute things as root? Uusually that is not a good idea, but maybe in docker world you need to do that?

**Comment by dalareo** [comment]
It is up to the user to do it, but at least now I know how to make jquery available when user is root. And yes, it is almost normal when using Docker, at least in development environments
