### ISSUE TITLE
Blank document

### ISSUE THREAD

**Issue by Doctor-Who** [fiduswriter/fiduswriter#337]
Hi,

Several user experiment strange issues, all document are empty : 
![image collee a 2016-12-1 10-37](https://cloud.githubusercontent.com/assets/5890416/20788860/a5e60fe4-b7b2-11e6-8ac4-b8faae9ae916.png)

I use latest version, try to do an update but nothing.
Try with Firefox, Chrome, Opera, but doesn't see difference

Best,

**Comment by johanneswilm** [comment]
What do you mean by latest version? If you are on a production platform, you are using version 3.0, right? 3.1 is not even in beta-mode yet.

Also, the error seems to be about no websocket connection. Could it be that the websocket port is blocked for some reason?

**Comment by johanneswilm** [comment]
Stockholm university library blocket the websocket port, for example.

**Comment by Doctor-Who** [comment]
Yeah people that experiment those problem have strict rules on their network ... how could I fix that ? (where can i see what is the version on my server ? i just follow update instruction on github)

**Comment by johanneswilm** [comment]
If it's super-strict, there is not much you can do. If they allow some ports and not others, you could try to change the port numbers. Look for 'WS_PORT' in the configuration.py file.

Also some users found that adblockers on their laptops were blocking their ports.

The server version number is found in version.txt. Unfortunately, if you are on 3.1, you cannot go back. I will make sure that the wording is very clear about that when we start the 3.2 development cycle.

**Comment by Doctor-Who** [comment]
I'm on 3.0.6
i gonna check configuration.py file thx

**Comment by johanneswilm** [comment]
Ok, good about the version number!

**Comment by Doctor-Who** [comment]
Thx for quick answering me.
I've check configuration.py file but I do not have WS_PORT mention in the file.
Should I add a new parameter ?

**Comment by johanneswilm** [comment]
Yes, add it to the SERVER_INFO section, like this:

```
SERVER_INFO = {
    ...
    'WS_PORT': 1234
}

**Comment by Doctor-Who** [comment]
Ok thanks so much, if they use url with port 8000 it works.
If they use an url done with Reverse Proxy, it's not working.
Got my answer, reverse proxy put the mess.
