### ISSUE TITLE
Line inserted before heading is not formatted as heading

### ISSUE THREAD

**Issue by clange** [fiduswriter/fiduswriter#392]
In other word processors I can insert a new heading as follows:

1. Go to the beginning of an existing heading (i.e. a line with style "Heading 1" etc.)
2. Press "return"
3. A new line will be inserted above the heading, and it will be formatted in the same "Heading N" style.

In FW the new line is styled as "normal".

@johanneswilm FYI this is something I learned during dogfooding, i.e. authoring an OSCOSS-related paper inside FW :-)

**Comment by johanneswilm** [comment]
True, it inserts a paragraph above the current line if one does right at the start of the line. But isn't that the more common usecase?

**Comment by johanneswilm** [comment]
This is working in current FW.
