### ISSUE TITLE
"Comment" button doesn't scroll comment into visible scope when there are many comments

### ISSUE THREAD

**Issue by clange** [fiduswriter/fiduswriter#395]
How to reproduce (with Chrome):
1. Attach a lot of comments to a document.
2. Pick a line in whose neighbourhood there are a lot of comments and scroll the document such that that line becomes visible.
3. add a new comment at a place that comes after the places annotated with the existing comment.
4. The new comment won't be visible to the user. It only becomes visible after manual scrolling.

Google Docs makes such new comments visible by shifting the comment boxes.

**Comment by johanneswilm** [comment]
This is working in FW 3.4+
