### ISSUE TITLE
It should be possible to "resolve" a thread of comments

### ISSUE THREAD

**Issue by clange** [fiduswriter/fiduswriter#396]
… once the discussion is over, so that it will be hidden and doesn't distract the view any more. Like in Google Docs. For being able to review and possibly restore resolved comment threads, this would, however, require an additional user interfaces that provides a second view on the comments.

**Comment by johanneswilm** [comment]
Is this any different than removing the comment?

**Comment by clange** [comment]
Yes, it is, because via the second view on the comments once can still see resolved threads (but not deleted ones) and can reopen them. Also when giving comments the semantics of tasks assigned to users (see #393), resolving is different from deleting. Think of an issue tracker: deleting means something like "invalid" or "wontfix". Resolving a thread in Google Docs also notifies the users who are in Cc.

**Comment by clange** [comment]
s/once can/one can/

**Comment by johanneswilm** [comment]
I see. good point.

**Comment by johanneswilm** [comment]
This has been added in Fidus Writer 3.5
