### ISSUE TITLE
latex exporter: function footnote does not work

### ISSUE THREAD

**Issue by jucajuca** [fiduswriter/fiduswriter#406]
Hi,

I created a document and I created footnotes. When I downloaded the document as a tex file the footnotes were empty. 
And it failed to compile in texmaker.

thx

**Comment by johanneswilm** [comment]
Could you share the output?

**Comment by johanneswilm** [comment]
Also, which browser/OS were you usng, @jucajuca ? And what error message did the latex compiler give you?

**Comment by jucajuca** [comment]
Attached the output.

In texMaker this line was the problem:
\usepackage[utf8]{luainputenc}

Still the footnotes are missing...

[great-document.latex (2).zip](https://github.com/fiduswriter/fiduswriter/files/848973/great-document.latex.2.zip)

**Comment by johanneswilm** [comment]
the missing footnotes should be in fixed in the 3.1 branch. The issue with luainputenc is most likely in how you use texmaker -- you need to run this with the lualatex engine, not pdftex or some other engine.

**Comment by johanneswilm** [comment]
The footnote issue has now also been fixed in the develop branch. Please test and close if the issue has been resolved for you, @jucajuca .

**Comment by jucajuca** [comment]
great, is working now :+1:
