### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by almereyda** [fiduswriter/fiduswriter#414]
Some Markdown editors like HackMD or StackEdit provide a `[TOC]` snippet to insert a table of contents into the document.

Which possibilities do I have with Fidus Writer to reach a similar goal, i.e. automatically built from the headline hierarchy?

**Comment by johanneswilm** [comment]
@almereyda One of our programmers is currently working on document internal links. This may be something that would be built on top of that for soem specific situations, but this is probably something that will have to be contributed from users like you as the very limited time we have on this will have to be focused on the more geenral usecases. And for those, a TOC would be something that can be added via the output filter: the CSS-for-print solution we use already has something like that built in (we only use it in the case of books), and of course Latex also provides it. You should probably also be able to create ODT/DOCX templates that include TOCs, if those formats have an auto-updating element for that (I haven't checked).

**Comment by almereyda** [comment]
Thanks, output filters sound a moveable path for this. If you have a label for such things, you could add *feature request*, *help wanted* or alike to defer this issue.

**Comment by johanneswilm** [comment]
I have "wontfix" :)  

No seriously, I have now added helpwanted, but please be aware that with 90% certainty, nothing is going to come of this unless you are someone you know will work on this.

**Comment by johanneswilm** [comment]
is availabel in develop version
