### ISSUE TITLE
Selected Word Count

### ISSUE THREAD

**Issue by almereyda** [fiduswriter/fiduswriter#415]
The current word count implementation only counts the whole document for words, and also mentions individual characters with or without spaces.

Are there plans to extend these features for selected character ranges only?

**Comment by johanneswilm** [comment]
@almereyda Is this something you want to contribute? That would be very welcome. The core team does not have any current plans to extend the word counter at this point.

**Comment by johanneswilm** [comment]
This has been added in version 3.7.20.
