### ISSUE TITLE
Removing links

### ISSUE THREAD

**Issue by almereyda** [fiduswriter/fiduswriter#416]
In a document I am writing, links can be created but not removed.
I have tried removing the link's URI and saving it, but nothing happens.

**Comment by johanneswilm** [comment]
Indeed, currently one simply has to remove all characters fo the link to remove it. That is maybe not what everyone would naturally do, so it would be good to have more options here.

**Comment by johanneswilm** [comment]
@almereyda Hey, this has now been added in the development version. It will land in the next stable version.
