### ISSUE TITLE
List CSS

### ISSUE THREAD

**Issue by almereyda** [fiduswriter/fiduswriter#417]
Creating many bullet points below each other enforces a paragraph padding, which spreads the bullets from each other.
Introducing line feeds via Shift-Return links the lines closer together, but removes the possibility of adding bullet points.

**Comment by johanneswilm** [comment]
Hey, well, yeah, but this is how CSS styling works. You can create a different CSS stylesheet that puts less space between paragraphs in bullet points and then use that. It doesn't seem to be a bug, or is there something I don't understand about the issue you are having, @almereyda ?

**Comment by almereyda** [comment]
Yes, I consider the paragraph tags in this example redundant:

```
<ol pm-container="true" pm-offset="188" pm-size="38">
    <li pm-container="true" pm-offset="0" pm-size="12">
        <p pm-container="true" pm-offset="0" pm-size="10"><span pm-offset="0" pm-size="8">bullet 1</span>
        </p>
    </li>
    <li pm-container="true" pm-offset="12" pm-size="12">
        <p pm-container="true" pm-offset="0" pm-size="10"><span pm-offset="0" pm-size="8">bullet 2</span>
        </p>
    </li>
    <li pm-container="true" pm-offset="24" pm-size="12">
        <p pm-container="true" pm-offset="0" pm-size="10"><span pm-offset="0" pm-size="8">bullet 3</span>
        </p>
    </li>
</ol>
```

They are what breaks the CSS flow:

```
.user-contents h1, .user-contents h2, .user-contents h3, .user-contents p, .user-contents blockquote, .user-contents code, .user-contents ol, .user-contents ul {
    margin-bottom: 35px;
}
```

**Comment by johanneswilm** [comment]
@almereyda This is something you can go discuss with everyone invovled in ProseMirror development at https://discuss.prosemirror.net .
