### ISSUE TITLE
collaboration workflows : invitation + anonymous

### ISSUE THREAD

**Issue by almereyda** [fiduswriter/fiduswriter#419]
For collaborating on a Fidus Writer document with peers, it is a requirement for them to sign up to the platform.
In terms of open collaboration, sometimes people don't want to register, but want to contribute by visiting a secret link.

Another question is the handling of invites to Fidus Writer, as currently this is just a `mailto:` link which doesn't add the desired user to the target document, if intended.

Probably those are two different issues, but they touch the same mechanics.

**Comment by johanneswilm** [comment]
Duplicate of #383 and #196 I believe?

**Comment by johanneswilm** [comment]
And maybe also #86 ?

**Comment by almereyda** [comment]
Yes.
