### ISSUE TITLE
import/export NLM/JATS

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/fiduswriter#42]
import and export from/to NLM/JATS would be interesting for some sciences

**Comment by BigBlueHat** [comment]
Useful. Perhaps. 😄 https://github.com/scienceai/dejats

**Comment by jobdiogenes** [comment]
The link https://github.com/scienceai/dejats, does not exist !

**Comment by johanneswilm** [comment]
Probably outdated. But these could be useful: https://www.le-tex.de/en/transpect.html or https://github.com/substance/dar

**Comment by jobdiogenes** [comment]
Great @johanneswilm , transpect looks promising. I don't know about the internal format of FidusWriter. But, from the point of view of simplicity, could be time consuming create and maintain a module to export to JATS-XML, in this way, as another option we could create a MD (MarkDown) and from then export to JATS.  What do you think? I'm really interest in helping in developing for a JATS-XML export.

**Comment by johanneswilm** [comment]
So first of all: I'd be very glad if we had such an exporter and I don't care too much how it's achieved as long as someone is willing to do it. Transpect would have the advantage of covering several import and export formats. And independently of that, the DAR subset of JATS in the second link could be a starting point for an export format, as I understand it that JATS has really many tags and it's impossible to cover them all. But I haven't really looked into the specifics, so what I'm saying may be completely wrong.

My suspicion with your proposal of using markdown as an intermediate format is that I would think that markdown cannot really cover everything about the FW format. Especially all the citation types and fields will probably be hard to convert that way. But I could be wrong if you have found a markdown flavor that covers it.

If I were to program this, I think I would look at the current ODT and DOCX exporters. They iterate over the JSON of the Fidus Writer document and create XML code which they then inject into existing XML files. I would think it would be the easiest to follow that same path to create JATS-XML files. But there is more than one way to skin a cat, so if you have a different idea and it works, that's also great.

Let me know if you end up working on this!

**Comment by jobdiogenes** [comment]
Oh, @johanneswilm , Thanks very much for your explanation. 
And for the great suggestion to start from ODT/DOCXML exporters. 
Yes, full JATS its very long, not so complex as MS DOCSXML (never try read that crazy specs).
I read almost all JATS specs, its well explained, but too long. 

But, for FidusWriter and other projects, an intermediate forma as DAR  could be more appropriate. 

Thanks again.

**Comment by johanneswilm** [comment]
@jobdiogenes JATS export has been implemented in the current development version. Will be released with FW 3.7.
