### ISSUE TITLE
HTML table support

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/fiduswriter#43]
support HTML tables. Currently all tables have to be included as SVG files.

**Comment by zeigerpuppy** [comment]
An HTML table editor would be nice, 

it may be even better if a table could be produced in R datatable format, then it would be quite natural to display data as an interactive web chart using http://www.htmlwidgets.org/showcase_datatables.html or as latex using knitr and xtables.

**Comment by johanneswilm** [comment]
@zeigerpuppy: there are several news items to this:

* One could already now include a table-as-widget. This would mean that only one person can edit the table at a time. Using R has been mentioned. If this cannot be done entirely in JavaScript, it will mean another dependency on the server which has to be justified.

* ProseMIrror (the text editing lib) has plans to have table support in the regular editor sometime in the near future. This would mean a table in the regular editor where several people can edit it at the same time.

* The OSCOSS project is planning on working on table support for Fidus Writer, and last I heard of them, they were thinking of data tables. @momenifi may know more.

**Comment by zeigerpuppy** [comment]
I agree that maintaining collaborative editing would be essential and keeping dependencies to a minimum is also desirable.  Interesting problem.

**Comment by johanneswilm** [comment]
Table support has been with us for a while now. More complex table support is also around the corner.
