### ISSUE TITLE
Empty documents and disabled menus

### ISSUE THREAD

**Issue by stonfute** [fiduswriter/fiduswriter#438]
I've made a fresh install following install guide on ubuntu 16.04

I've imported some documents from another instance (using fidus format).
When I try to open a file all menus are disabled and the document is empty. > No error in console

 When i make a new document, it's the same ! I can type data but when i close and open it again the document looks empty. 
![screeshot](https://cloud.githubusercontent.com/assets/10881783/26196541/91e92f6c-3bbf-11e7-8d6b-26102cb8330b.PNG)

**Comment by johanneswilm** [comment]
@stonfute Hmm, this doesn't happen here. Could you sent me such a doc? Maybe I could find something about it? I understand there are no errors in the console, but maybe on the server?

**Comment by johanneswilm** [comment]
@stonfute And which branch is this on?

**Comment by johanneswilm** [comment]
@stonfute And what browser? (also, version number)

**Comment by johanneswilm** [comment]
@stonfute Ping! Could we get some more info on this? We are just about to release version 3.2, but if this is a serious bug, we'll have to fix it first.

**Comment by johanneswilm** [comment]
@stonfute As there has been no response from you for the past few weeks, I assume this is an issue on your side that we cannot help much with and I'm closing the issue. Please feel free to reopen it if you have more information.
