### ISSUE TITLE
Editor not working

### ISSUE THREAD

**Issue by jucajuca** [fiduswriter/fiduswriter#461]
Hello
I installed fiduswriter on my pi. I tried both the "manual" and the docker method. However with both methods the editor is not working properly (everything else seems to work normally) 

![screenshot from 2017-07-08 23-11-20](https://user-images.githubusercontent.com/24567185/27989176-46306774-6433-11e7-88a9-10871a03dbe1.png)

Any ideas of what could be the problem? thank you!

**Comment by johanneswilm** [comment]
If everything else was working up to that point, it looks like the websocket connection is not working. There are several possible reasons for this, for example:
* an anti-virus program on your client blocking websocket
* something on the local network prohibiting websocket connections
* your server is set up only for regular http traffic
* You are somehow running this on regular DJango: most of the pages are served via regular Django, but the websocket part is served through some other mode offered by tornado so this will only work if you use the builtin mixed django-tornado server that comes with FW. If you follow the instructions to the letter, this should be happening, but if you diverge in any way, all bets are off.

I think this is as much as I can say at this stage.

**Comment by jucajuca** [comment]
yes that seems to be the problem. It seems that Apache is forwarding the requests to Tornado because I get following error from fiduswriter in the command line:

WARNING:tornado.access:400 GET /ws/document/0 (195.230.41.42) 4.07ms
 
Below is a copy of the request headers.

I think it is a problem with the communication between apache and tornado. Do I have to rewrite the request in any form, or does it need some extra headers? 

```
Request URL:wss://latex.juan-carlos.info/ws/document/0
Request Method:GET
Status Code:400 Bad Request

Response Headers

Connection:close
Content-Length:34
Content-Type:text/html; charset=UTF-8
Date:Sun, 09 Jul 2017 09:33:23 GMT
Server:TornadoServer/4.5.1

Request Headers

Accept-Encoding:gzip, deflate, br
Accept-Language:de,en-US;q=0.8,en;q=0.6,es-419;q=0.4,es;q=0.2
Cache-Control:no-cache
Connection:Upgrade
Cookie:sessionid=kp3o3puba9scupapirrcfunbs2v38r3v; messages="b27bcc3513d47bb456bf8059f5e9e81e402cec6f$[[\"__json_message\"\0540\05425\054\"Erfolgreich als jjjj angemeldet.\"]]"; csrftoken=aFiqID2z1NrRdZWA1Rdn2Hq97NWOtdHxnQJftcslgDkUO3awaeR2izifXbDqOaQd
Host:lelele.juan-carlos.info
Origin:https://lelele.juan-carlos.info
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:P027OfoPv8QP0ILn3prY9A==
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
```

**Comment by johanneswilm** [comment]
Hey,
yes apache won't work. Apache is not mentioned anywhere in the install instructions either. There may be ways of doing that, and we would be very interested in you writing up how to get it to work by means of an entry into the wiki if you choose that route, but we can only give support if you follow the instructions.

So please, follow the instructions. :) 

In the wiki there are instructions for how to get it to run beihidn nginx, if you want to run it behind another server.

**Comment by jucajuca** [comment]
Hi,
This seems to work.

```
<VirtualHost *:443>

	ServerName yourserver.com
	DocumentRoot /var/www/html
	<Directory />
		Options FollowSymLinks
		AllowOverride All
	</Directory>

	ServerAdmin you@yourserver.com

        ProxyPreserveHost On
        ProxyRequests off

	RewriteEngine on
	RewriteCond %{REQUEST_URI} ^/ws [NC,OR]
	RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
	RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
	RewriteRule .* ws://127.0.0.1:8000%{REQUEST_URI} [P,QSA,L]

        ProxyPass / http://127.0.0.1:8000/
        ProxyPassReverse / http://127.0.0.1:8000/

#other directives etc...

</VirtualHost>
```

You might also need to deactivate the apache firewall or at least some rules.

**Comment by jucajuca** [comment]
It is working so far. 
I edited the wiki entry with this changes.
cheers!

**Comment by johanneswilm** [comment]
This is very cool! Very nice, @jucajuca !
