### ISSUE TITLE
ODT/DOCX not working

### ISSUE THREAD

**Issue by jucajuca** [fiduswriter/fiduswriter#464]
Hi,

I installed FW. Is running fine so far, but I can't get the ODT filter to work. (And I really need it)
I set "experimental" to True, but I still don't see the menu item. It just shows latex, html, epub.
Do I need to re-trasnpile the js files with the option experimental activated?

thx!

**Comment by johanneswilm** [comment]
Which branch are you on? You should be on master. What you are describing
makes it sound like you have no export templates registered. There are
fixtures for an ODT and DOCX template that should be installed
automatically during the install procedure ( ./manage.py init). Did you see
any errors during that part?

**Comment by jucajuca** [comment]
well now that you mention it... I got these errors. The first ones are fonts and the sencond ones are indeed the templates for odt / docx... maybe they are missing in the repo? ; )

`Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/NoticiaText-Bold_2.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/NoticiaText-Regular.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/NoticiaText-Italic.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/NoticiaText-BoldItalic.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/SourceSansPro-Bold.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/CrimsonText-Roman.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/CrimsonText-Bold.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/CrimsonText-Italic.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/CrimsonText-BoldItalic.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/Lobster-1.4.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/Cardo-Regular.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/Cardo-Bold.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/Cardo-Italic.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/OpenSans-Regular.woff doesn't exist, skipping
Expected file at /var/www/fiduswriter/document/fixtures/media/document-fonts/OpenSans-Bold.woff doesn't exist, skipping


Installed 32 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)


Expected file at /var/www/fiduswriter/style/fixtures/media/export-templates/template.docx doesn't exist, skipping
Expected file at /var/www/fiduswriter/style/fixtures/media/export-templates/template.docx doesn't exist, skipping
Expected file at /var/www/fiduswriter/style/fixtures/media/export-templates/template.docx doesn't exist, skipping
Expected file at /var/www/fiduswriter/style/fixtures/media/export-templates/template.odt doesn't exist, skipping
Expected file at /var/www/fiduswriter/style/fixtures/media/export-templates/template.odt doesn't exist, skipping
Expected file at /var/www/fiduswriter/style/fixtures/media/export-templates/template.odt doesn't exist, skipping
Installed 2 object(s) from 1 fixture(s)`

**Comment by johanneswilm** [comment]
Hey,
no, we have many installations and none have issues, so nothing is missing in the repos. :)

This error is normal, strangely it is looking for the fixture files in ALL of the possible directories and is outputting this error is it cannot be found in ALL of them. Of course, it is really enough for them to be in ANY of the possible directories. The very last line says that the two template files were installed correctly:

    Installed 2 object(s) from 1 fixture(s)

So after running this, DOCX and ODT still do not show up in your menus?

**Comment by johanneswilm** [comment]
Could you check via the Django admin menus whethr any export templates are listed there? At `/admin/document/exporttemplate/`

**Comment by jucajuca** [comment]
No nothing listed there. But when I click in "add template" then I get the dropdown menu with 
docx and odt. Should I just submit the templates in "./fiduswriter/document/fixtures/media/export-templates/"?

![image](https://user-images.githubusercontent.com/24567185/28263011-8b5cf188-6ae5-11e7-9dfd-16cc77f00d30.png)

**Comment by johanneswilm** [comment]
Yes try that, but then that shows that some part of the installation is
failing. Hopefully it's only this.

**Comment by jucajuca** [comment]
cool, I think is working now. I'll test it for a while.
