### ISSUE TITLE
Spell / grammar inserts at cursor instead of word

### ISSUE THREAD

**Issue by wes-r** [fiduswriter/fiduswriter#530]
Steps to reproduce:
* Type a misspelled or grammatically incorrect word.
* Run spell/grammar checker
* select word for fix
* move cursor
* click correction

Bug:
The correction is replacing the selected text instead of the triggering word/phrase.

![oct-06-2017 12-04-11](https://user-images.githubusercontent.com/1568246/31287297-c677d79a-aa8e-11e7-805a-2f7f79688b2d.gif)

**Comment by johanneswilm** [comment]
Good point. That we can fix in various ways. But there is also the case where a collaborator changes the text while the dialog is open and then we can really do much about it.

**Comment by wes-r** [comment]
If you store the word and location you should be able to either:
1. ignore correction since the triggering condition is no longer valid
2. detect change and auto close the dialog box (may be confusing to users though).. alternatively you could show a message in the box and disable the correction options.

**Comment by johanneswilm** [comment]
Yeah, hard to know how 'real users' will react.  Maybe I'll try this:
* make the modal dialog so that one cannot manually change the selection.
* don't apply any change if the selection is collapsed at the time the button is pressed.

And then see how non-technical users react to that.

**Comment by wes-r** [comment]
My guess is that will satisfy 99.9% of uses. Should be fairly rare for a user to have the dialog open while another user changes the word from under them.

**Comment by johanneswilm** [comment]
Fixed in https://github.com/fiduswriter/fiduswriter-languagetool/commit/16b1967872f0e76962984ecabfd28e272aa8406d
