### ISSUE TITLE
Label and Caption, Table and Figures and dynamic refs. 

### ISSUE THREAD

**Issue by jobdiogenes** [fiduswriter/fiduswriter#586]
Insert a dynamic (auto numbering) reference to Table and Figures in text is an ordinary task for scientific writing, which exist in editors for ODT, DOCX, Latex, etc.

In that way is important to have auto-numbering and Label and Caption fields  for Table and Figures, which could enhance FidusWriter editor and the exporter quality for Latex, ODT, DOCX, etc.

**Comment by johanneswilm** [comment]
@jobdiogenes There are labels and auto numbering for figures already. Not for tables.

**Comment by johanneswilm** [comment]
@jobdiogenes What are you thinking in terms of dynamic refs? You probably noticed it has the capability to link to headlines and figures, which have automatic unique IDs.

**Comment by nmueller18** [comment]
I think this is an important issue as well. The referencing of figures works very well and as expected. Tables should in this way treated like figures, that means with their own caption and numbering and the possibility to link to them.

**Comment by johanneswilm** [comment]
Table captions and numbering are available in Fidus Writer 3.9.
