### ISSUE TITLE
tracking tests

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/fiduswriter#613]
We need integration tests to test tracking.

**Comment by pintomollo** [comment]
Hi Johann, I'll use this feature quite extensively in the coming weeks with my student. Let me know if we could help. Cheers

**Comment by johanneswilm** [comment]
Hey,
yes, we need automatic Selenium tests for this. We used a Firefox plugin to create the tests for other parts of the app initially and then adjusted them a bit to work with our infrastructure. I don't know if that plugin still is working, but I can see there is a similar one for Chrome called Katalon [1] now.

[1] https://chrome.google.com/webstore/detail/katalon-recorder/ljdobmomdgdljniojadhoplhkpialdid

**Comment by pintomollo** [comment]
Hi Johannes,

I am not familiar with either. Could you be a bit more explicit on what is
required here and point me at the related test code that you want to run?

Cheers,
Simon

Le jeu. 21 févr. 2019 à 22:33, Johannes Wilm <notifications@github.com> a
écrit :

**Comment by johanneswilm** [comment]
Hey @pintomollo ,
yes so the test code is what I need to be produced. This can largely be done by a non-programmer. Just install for example the Selenium-IDE Chrome browser extension and record a test where one turns on tracking changes in Fidus writer and then does a number of basic operations such as writing some text, approving an insertion, deleting some text, adding and deleting a figure, turning a headline 2 into a headline 3, etc. . Basically do everything that you need to be able to do when tracking changes. Every now and then click the right mouse button, select the "Selenium IDE" submenu and choose one of the options there to verify that the screen shows what is it is supposed to show. For example make sure there is a box on the right hand side saying "insertion" after having written some tracked text. 

Selenium IDE will then create a test script which can be exported in Python language. With a few manual fixes to it, it can then be added to the Fidus Writer repository to always run when changes are applied to make sure they are not breaking anything. See for example this [1] which tests whether collaboration works correctly. The code in Fidus Writer that adds tracked changes is this [2].

[1] https://github.com/fiduswriter/fiduswriter/blob/develop/document/tests/test_collaboration.py

[2] https://github.com/fiduswriter/fiduswriter/blob/develop/document/static/js/modules/editor/track/amend_transaction.js

**Comment by johanneswilm** [comment]
Basic test have been added
