### ISSUE TITLE
Translations and other metadata

### ISSUE THREAD

**Issue by jobdiogenes** [fiduswriter/fiduswriter#626]
For authors that deal with only one language its Ok to work with just one version of fields like:
- title
- abstract 
- keywords
- author notes 

But, for  many users and Countries that does not have English as first Language, its a common task you have to write these parts above in dual language version.

Well, I think that its really a mandatory feature FidusWrites has  support for language versions of fields parts. 

One way to deal with this, is to have custom metadata fields, and there the option to use/get the field name used in text. There's could have a tag for language, a field name (new or basic) and the value.

**Comment by johanneswilm** [comment]
Indeed. Also, there may have to be several translations of title and abstract (observed: German, French, English), and more optional sections (observed: an extra bibliography with items not mentioned in the text).

So yes, we either need to enlarge the number of document parts or make some of the document parts optional and allow arbitrary numbers o the same element in different languages.

Either way, it is likely to make the user interface somewhat more complicated, and also filters will need to be reworked.

**Comment by johanneswilm** [comment]
this is present in the develop branch
