### ISSUE TITLE
\printbibliography after \end{document}

### ISSUE THREAD

**Issue by jucajuca** [fiduswriter/fiduswriter#632]
Hi I just exported a latex document. I noticed that \printbibliography comes after \end{document}. I think it should come before ; )

\section{Bibliography}

\end{document}

\printbibliography

**Comment by johanneswilm** [comment]
@jucajuca What version of Fidus Writer are you running? According to my logs, this was fixed December 27 2017. I cannot reproduce it on the main site either.
