### ISSUE TITLE
How do I make the Fidus Writer run persisent on the Ubuntu server?

### ISSUE THREAD

**Issue by jogibjorn** [fiduswriter/fiduswriter#673]
I've installed Fidus Writer on Ubuntu 18. I use SSH to login and startup with `./manage.py runserver`, but how do I leep it running after I close the SSH session. At the moment its only "live" as long as the SSH session is running.

**Comment by jogibjorn** [comment]
I managed to get it starting on boot by putting the `run_fiduswriter.sh` in Cron
`@reboot /home/xx/run_fiduswriter.sh`

**Comment by johanneswilm** [comment]
Hey @jogibjorn You did look into the readme which told you to look at the Wiki, right? Because that's where you can find that information. ;)

**Comment by johanneswilm** [comment]
@jogibjorn https://github.com/fiduswriter/fiduswriter/wiki/Advanced-Configuration-on-Ubuntu#automatic-restart-of-server
