### ISSUE TITLE
Unable to change collaborators' access rights

### ISSUE THREAD

**Issue by sergioatt** [fiduswriter/fiduswriter#679]
In File>Share: **Share your document with others**, the drop down listing the various access rights is partially hidden, so no other rights other than "basic" can be selected.

Tested on Chrome and Firefox.

![fidus writer - change access rights](https://user-images.githubusercontent.com/45259300/48898423-a4827500-ee44-11e8-851c-c5b83371d238.png)

**Comment by hendrikjandetuinman** [comment]
Same problem here. Is this a CSS issue maybe ?

**Comment by johanneswilm** [comment]
Yes, a CSS issue.

**Comment by pintomollo** [comment]
Confirming the same issue, but only with Firefox (Quantum 65.0, Unbuntu 18.04). Works fine with Chrome.
