### ISSUE TITLE
npm 84 vulnerabilities

### ISSUE THREAD

**Issue by m-schmale** [fiduswriter/fiduswriter#716]
Hi,

Could you please tell me how to fix these 84 vulnerabilities?
"npm audit fix" could not do it. Unfortunately, my knowledge of Linux is still very limited.

npm -v: 6.5.0

Example:

High - Regular Expression Denial of Service 
Package: tough-cookie
Patched in: >=2.3.3
Dependency of: npm-check-updates [dev]
Path: npm-check-updates > npmi > npm > request > tough-cookie
More info: https://nodesecurity.io/advisories/525

Thanks,
Mark

**Comment by johanneswilm** [comment]
this has been fixed. It was not directly FW related: these were dependencies of npm check updates. We have switched to the `updates` package which doesn't have these issues
