### ISSUE TITLE
New line command doesn' t work as expected. It' s releated to the cursor position

### ISSUE THREAD

**Issue by JoYellow** [fiduswriter/fiduswriter#719]
Creating a new document you can insert as many new line as you want. From the second time you open that document you are not able to insert as many new line as you want, but just one. The issue seems related to the number of character on that row. if it' s 0 you can' t move the cursor to the next line. If you add a character then you can insert also a new line (pressing enter). 
Different behaviour occurs if the body of the document is empty. In that case you can add as many spaces you want,also after the first time you open the document, but if you type some characters the issue is still the same.

**Comment by JoYellow** [comment]
I noticed an imprecision in the previous comment. You are able to insert new lines when the body is empty
![screenshot from 2019-02-08 19-03-29](https://user-images.githubusercontent.com/45432233/52496717-65a6c480-2bd4-11e9-9c80-5c1c186956f7.png)

in detail you are able to add a new line only if your cursor is in the same position as in the image. If you move the cursor to the previous line you are not able to add a new line.

**Comment by JoYellow** [comment]
This issue is not related to the number of times you opened the document. It depends just to the cursor position. (sorry for the imprecisions in reporting this issue)

**Comment by johanneswilm** [comment]
@JoYellow Ok, but if there is an empty line below the one you are currently on - why would you want to create another empty line?

**Comment by JoYellow** [comment]
in the previous version of fidus(at https://app.fiduswriter.org) it is possible, like in any other text editor. Maybe has no practical sense but do you think it s intuitive for the user ? My first impression was that something was not working.

**Comment by johanneswilm** [comment]
I'm not sure if this is something we have done or whether it comes from PM. The reason why one may want to stop this is people who enter 20 line breaks in order to move something to the next page because they haven't quite understood how page breaks work.

I can try to investigate.

**Comment by JoYellow** [comment]
ok thanks
