### ISSUE TITLE
book plugin has install error

### ISSUE THREAD

**Issue by mrchristian** [fiduswriter/fiduswriter#768]
Hi,

I'm moving over an issue from the Fidus Writer forum.

https://forum.fiduswriter.org/d/41-book-plugin-install

We are getting an error when trying to install the Book plugin. We have followed and completed all the instruction for installing and running fidus writer. Our installation has been running for a week or so while we have been doing user testing.

Then when we try to install the book plugin it fails.

It's on a clean Ubuntu 18.04 install, using Nginx.

Thanks for your help

Simon

Here is the error log again:

(venv) fidus3@guard:~/fiduswriter$ ./manage.py init
Operations to perform:
Apply all migrations: account, admin, auth, avatar, bibliography, book, contenttypes, document, feedback, flatpages, sessions, sites, socialaccount, style, user, usermedia
Running migrations:
Applying contenttypes.0001_initial... OK
Applying auth.0001_initial... OK
Applying account.0001_initial... OK
Applying account.0002_email_max_length... OK
Applying admin.0001_initial... OK
Applying admin.0002_logentry_remove_auto_add... OK
Applying admin.0003_logentry_add_action_flag_choices... OK
Applying contenttypes.0002_remove_content_type_name... OK
Applying auth.0002_alter_permission_name_max_length... OK
Applying auth.0003_alter_user_email_max_length... OK
Applying auth.0004_alter_user_username_opts... OK
Applying auth.0005_alter_user_last_login_null... OK
Applying auth.0006_require_contenttypes_0002... OK
Applying auth.0007_alter_validators_add_error_messages... OK
Applying auth.0008_alter_user_username_max_length... OK
Applying auth.0009_alter_user_last_name_max_length... OK
Applying avatar.0001_initial... OK
Applying avatar.0002_add_verbose_names_to_avatar_fields... OK
Applying avatar.0003_auto_20170827_1345... OK
Applying bibliography.0001_squashed_0011_auto_20170101_1647... OK
Applying document.0001_squashed_0032_document_listed... OK
Applying usermedia.0001_squashed_0009_auto_20170908_0953... OK
Applying book.0001_initial... OK
Applying book.0002_auto_20151226_1110... OK
Applying book.0003_auto_20160515_1007... OK
Applying book.0004_auto_20160515_1008... OK
Applying book.0005_auto_20160515_1013... OK
Applying style.0001_squashed_0002_auto_20151226_1110... OK
Applying document.0002_auto_20180814_1946... OK
Applying document.0003_auto_20181115_0926... OK
Applying document.0004_documenttemplate... OK
Applying document.0005_document_template... OK
Applying document.0006_auto_20190118_1342... OK
Applying document.0007_auto_20190227_2105... OK
Applying feedback.0001_initial... OK
Applying sites.0001_initial... OK
Applying flatpages.0001_initial... OK
Applying sessions.0001_initial... OK
Applying sites.0002_alter_domain_unique... OK
Applying socialaccount.0001_initial... OK
Applying socialaccount.0002_token_max_lengths... OK
Applying socialaccount.0003_extra_data_default_dict... OK
Applying user.0001_squashed_0003_auto_20151226_1110... OK
Installed 32 object(s) from 1 fixture(s)
Installed 2 object(s) from 1 fixture(s)
Installed 2 object(s) from 1 fixture(s)
processing file django.po in /home/fidus3/fiduswriter/locale/fr/LC_MESSAGES
processing file djangojs.po in /home/fidus3/fiduswriter/locale/fr/LC_MESSAGES
processing file django.po in /home/fidus3/fiduswriter/locale/BASE/LC_MESSAGES
processing file djangojs.po in /home/fidus3/fiduswriter/locale/BASE/LC_MESSAGES
processing file django.po in /home/fidus3/fiduswriter/locale/pt_BR/LC_MESSAGES
processing file djangojs.po in /home/fidus3/fiduswriter/locale/pt_BR/LC_MESSAGES
processing file django.po in /home/fidus3/fiduswriter/locale/de/LC_MESSAGES
processing file djangojs.po in /home/fidus3/fiduswriter/locale/de/LC_MESSAGES
processing file django.po in /home/fidus3/fiduswriter/locale/bg/LC_MESSAGES
processing file djangojs.po in /home/fidus3/fiduswriter/locale/bg/LC_MESSAGES
processing file django.po in /home/fidus3/fiduswriter/locale/it/LC_MESSAGES
processing file djangojs.po in /home/fidus3/fiduswriter/locale/it/LC_MESSAGES
processing file django.po in /home/fidus3/fiduswriter/locale/es/LC_MESSAGES
processing file djangojs.po in /home/fidus3/fiduswriter/locale/es/LC_MESSAGES
Traceback (most recent call last):
File "./manage.py", line 28, in <module>
execute_from_command_line(sys.argv)
File "/home/fidus3/venv/lib/python3.6/site-packages/django/core/management/init.py", line 381, in execute_from_command_line
utility.execute()
File "/home/fidus3/venv/lib/python3.6/site-packages/django/core/management/init.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/home/fidus3/venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
self.execute(args, cmd_options)
File "/home/fidus3/venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
output = self.handle(args, options)
File "/home/fidus3/fiduswriter/base/management/commands/init.py", line 43, in handle
call_command("transpile")
File "/home/fidus3/venv/lib/python3.6/site-packages/django/core/management/init.py", line 148, in call_command
return command.execute(args, defaults)
File "/home/fidus3/venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
output = self.handle(args, options)
File "/home/fidus3/venv/lib/python3.6/site-packages/npm_mjs/management/commands/transpile.py", line 68, in handle
npm_install = install_npm()
File "/home/fidus3/venv/lib/python3.6/site-packages/npm_mjs/management/commands/npm_install.py", line 78, in install_npm
call(["npm", "install"])
File "/usr/lib/python3.6/subprocess.py", line 267, in call
with Popen(*popenargs, **kwargs) as p:
File "/usr/lib/python3.6/subprocess.py", line 709, in init
restore_signals, start_new_session)
File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm': 'npm'

**Comment by johanneswilm** [comment]
Hey,
What output do you get if you run:

```
which npm
```

The `./manage.py init` command only needs to be run a single time when you first install Fidus Writer. You should not need to run it again when installing a plugin. Nevertheless, it should not give you that error.

To install the book plugin, follow these instructions: https://github.com/fiduswriter/fiduswriter-books/blob/master/README.rst (I updated them a minute ago).

**Comment by mrchristian** [comment]
Hi,

Thank you for the instruction updates, these worked. Great thank you. 

We also cleared the npm caches this may also make a difference.

The plugin now works but not entirely clear what was wrong.

There are issues with output formats not outputting in the book area, while still working in the documents area. I will raise this as a separate issue.

Thanks

Simon
