### ISSUE TITLE
book plugin outputs not working

### ISSUE THREAD

**Issue by mrchristian** [fiduswriter/fiduswriter#771]
Hi,

We have the book plugin installed and working. Thank you for the support in getting this to work.

The plugin is functioning and we can collate documents into a book.

But we are having a problem with outputs from the book area of the site, outputs from documents work.

In the book area only LaTeX output works.

Here is a error log from the Chrome browser console output.

Thanks

Simon

Log

app.js:33941 

Uncaught (in promise) TypeError: Cannot read property 'querySelectorAll' of undefined
    at EpubBookExporter.cleanHTML (app.js:33941)
    at app.js:5156

End log

**Comment by johanneswilm** [comment]
Ok, let's see.

Which version of the plugin did you install? And which version of Fidus Writer do you have running?

The versions need to correspond - so if you have Fidus Writer from the master branch (3.5.x), you need to have the plugin version 3.5.x. or if you are running Fidus Writer from the develop branch (3.6.0-rc.X), you need to use the plugin version 3.6.0-rc.1 .

If this is not it, then it would probably help if you could send me some chapter files as fidus files.

**Comment by mrchristian** [comment]
Hi,

If we are using the master, so 3.5.10

https://github.com/fiduswriter/fiduswriter/tree/master

Does this mean that mean for example with the book module that we need to set the Fidus Writer version on install, so would this be done like so:

https://github.com/fiduswriter/fiduswriter-books

quote

pip install "fiduswriter-books 3.5.10"

end quote

Thanks

Simon

**Comment by johanneswilm** [comment]
I think it's 

```
pip install "fiduswriter-books<3.6"
```

or 

```
pip install fiduswriter-books==3.5.1
```

**Comment by mrchristian** [comment]
Hi,

Well try pip install fiduswriter-books==3.5.1 first

Would this be the same for the other plugins, like 

pip install "fiduswriter-languagetool==3.5.1"

pip install "fiduswriter-citation-api-import==3.5.1"

Thanks

Simon

**Comment by johanneswilm** [comment]
The two first numbers have to correspond to the Fidus Writer version. So all Fidus Writer 3.5.X versions should be compatible with all 3.5.X versions of the plugins. The last number (the patch version) only indicates minor changes due to bugs we have found after release, and so they should not influence compatibility. In the case of the books plugin there has only been a 3.5.0 and a 3.5.1 version, but that could be different for other plugins. You can search the plugins on PyPi to see what version numbers exist for them: https://pypi.org/project/fiduswriter-books/ . In general, it is more likely there are more patch releases of the main program than of the plugins.

**Comment by mrchristian** [comment]
Hi,

Ah https://pypi.org/project/fiduswriter-books/  great thanks

I will try the following:

pip install fiduswriter-books<3.6

this would seem best, as then we catch the highest version, as for books the highest is 3.5.1, and with the other two plugins the highest is 3.5

BTW spelling is working, although import citations from DBs is loading and can search DBs, but the import isn't working, maybe we need a key for importing citations? I'll investigate further and report an issue for this if needed.

Thanks for your help, much appreciated

Simon

**Comment by johanneswilm** [comment]
> this would seem best, as then we catch the highest version

exactly, that's why that is the recommended way of doing it.

>  although import citations from DBs is loading and can search DBs, but the import isn't working, maybe we need a key for importing citations

When I recently updated the plugin to 3.6, it seemed to work without updates. However, unfortunately some of the databases are less stable in their API than what I had hoped and so in the past several updates had to be made at random times to accommodate for this. This may have happened again.

**Comment by mrchristian** [comment]
Hi,

Thank you for your help.

Citation DB not such a big issue, more a luxury.

What is important is the book plugin.

I'll report back later tonight or tomorrow when we have checked the install. As I mentioned its only the exports that are not working.

FYI I emailed full error logs to you as just concerned they might have sensitive data in them.

Thanks

Simon

**Comment by mrchristian** [comment]
Hi,

All three plugins: book, language, and citations now have v 3.5.0 installed.

I will not test the language and citation further as not a priority.

The book plugin still doesn't create the outputs.

I have attached the files from the documents and the book. I can download the docs as .fidus and the book will only export LaTeX.

Filles below:

Thanks

Simon

[hello.latex (2).zip](https://github.com/fiduswriter/fiduswriter/files/2989510/hello.latex.2.zip)
[Downloads.zip](https://github.com/fiduswriter/fiduswriter/files/2989513/Downloads.zip)

**Comment by mrchristian** [comment]
I also send  error logs via email from outputs of book from: HTML, PDF and EPUB.

Thanks

Simon

**Comment by johanneswilm** [comment]
Hey Simon,

those two document files were created with some pre-version of Fidus Writer 3.6.0 - so most likely the develop branch of Fidus Writer. I can tell by the filetype version. Given that we are just about to release 3.6.0, that is OK, but you then need to install the plugins that correspond to version 3.6.

**Comment by johanneswilm** [comment]
You should probably update your Fidus Writer version to the absolute latest so that you get all fixes that have come in the past few weeks.

**Comment by mrchristian** [comment]
Hi J,

Thanks for the help here.

I have done what you said and gone to the newest version.

Book and language plugins function now, thank you. We will keep the citation database plugin on a Test version  but for a production version not include as it currently doesn't fully work, in that the final 'import' button doesn't import the citation.

Maybe a review of the install instructions is needed to tell the user whether they should be using stable  'master' or pre releases should be used.

Now we're cooking though :-) We will setup a MySQL version and test against SQLite to see about performance issues in real-time collaborative editing.

Thanks again

Simon

**Comment by johanneswilm** [comment]
Hey Simon,
I just tied the citation-api-import with both sources from Datacite and from the GESIS Search. In both cases the Import-button worked. Could you give me an example of a work that you tried to import that did not work?

Updating the install instructions is a good idea. It's a wiki and you guys should be able to edit it directly.

**Comment by mrchristian** [comment]
Hi,

Citation import.

I searched for the DOI 10.25815/qx24-8m92

The DOI comes up from Datacite

I get error reports in my Chrome console and from the system, console error report is below, system log I'll post.

But essentially the import function doesn't work for any citations found.

[f1-test.consortium.io-1553179665873.log](https://github.com/fiduswriter/fiduswriter/files/2992552/f1-test.consortium.io-1553179665873.log)

I have sent the server logs via email

Yep. We'll get down to some Wiki suggestions and edits next week.

Thanks

Simon

**Comment by johanneswilm** [comment]
Most of those issues have been fixed in 3.6.0-rc.2. However, I can see that for example Gesis returns error messages on certain queries. That's really something for them to fix.

**Comment by mrchristian** [comment]
Hi,

Thanks. I'll look into rc.2, much appreciated.

We'll keep citation DB import on our DEV instance until we work it out, but other modules working well.

Our testing will now move onto collaborative editing and running a full example book or two through the system. This will happen over next week.

Looking good.

Thanks

Simon

**Comment by johanneswilm** [comment]
It seems like the original issue here has been resolved, so I am closing this issue.
