### ISSUE TITLE
Comment Bug 2.0  -  Cancel button deletes the comment

### ISSUE THREAD

**Issue by regostar** [fiduswriter/fiduswriter#789]
Bug :- Create new comment, submit and then click cancel would lead to the loss of a comment

Steps to recreate the bug :-
1. Make a comment then click submit
2. Now the comment answer is active, most of the users tend to click on cancel to stop adding a comment answer.
3. The whole comment is deleted

![image](https://user-images.githubusercontent.com/26195098/55499384-808d3680-5663-11e9-8298-dc5aeaccfd3e.png)

**Comment by johanneswilm** [comment]
This has been fixed.
