### ISSUE TITLE
upgrading to 3.6.0 -rc.19

### ISSUE THREAD

**Issue by mrchristian** [fiduswriter/fiduswriter#794]
Hi 

We got the following warning when upgrading to 3.6.0 -rc.19

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN rollup-plugin-terser@4.0.4 requires a peer of rollup@>=0.66.0 <2 but none was installed.

and then

| +-- UNMET PEER DEPENDENCY rollup@>=0.66.0 <2

we are working on Ubuntu 18.04

The Fidus Writer instance runs but would be good to know how to satisfy this dependency.

Thanks

Simon

**Comment by johanneswilm** [comment]
Those error messages are of no concern.
