### ISSUE TITLE
Citation Database import

### ISSUE THREAD

**Issue by mrchristian** [fiduswriter/fiduswriter#795]
Hi,

I have noticed that the Bibliography Database Import function works in one area of Fidus Writer and not in another. 

This is using the following Fidus Writer version 3.6.0 -rc.19

When in a document the Database Importer works.

If I am in the dedicated Bibliography are it doesn't work.

When I say works I am meaning 'successfully imports a specific bibliographic record'.

Thanks

Simon

**Comment by johanneswilm** [comment]
Hey @mrchristian What exactly is not working there? If I try to upload a *.bib file on the overview page, it does show new entries for me. If there is a particular file that is not working, would you mind sending me that file?

**Comment by johanneswilm** [comment]
Ah, @mrchristian , I think I now understand what you mean - you mean the API plugin?

Yes that was a known issue. It was fixed in version 3.6.0-rc.2 of the plugin about a month ago. Version 3.6.0 of the plugin was released 3 weeks ago. it is recommended to upgrade to that version.

**Comment by johanneswilm** [comment]
Please reopen if my guess was incorrect.
