### ISSUE TITLE
Upgrading to 3.6.1 and 3.6.2

### ISSUE THREAD

**Issue by mrchristian** [fiduswriter/fiduswriter#796]
Hi,

Our Fidus Writer instance has been on the 'release candidate' versions of Fidus Writer and we are now on 3.6.0 -rc.19.

Are there special considerations we should take into considerations if we want to upgrade to 3.6.1 and 3.6.2.

Many thanks

Simon

**Comment by johanneswilm** [comment]
No. You can just upgrade.
