### ISSUE TITLE
LGTM Warnings

### ISSUE THREAD

**Issue by MatheusRV** [fiduswriter/fiduswriter#800]
14 Warnings

7 alerts of Incomplete string escaping or encoding in escape_latex.js
1 alert of Insecure randomness in comment.js
3 alerts of Superfluous trailing arguments across 3 files
1 alert of Unvalidated dynamic method call in index.js
2 alerts of Useless assignment to local variable across 2 files

https://lgtm.com/projects/g/fiduswriter/fiduswriter/alerts/?mode=tree

**Comment by johanneswilm** [comment]
Hey @MatheusRV . Thanks for that. I have taken a look at those test results and unfortunately all 14 of them are incorrect. We have our own eslint setup to find issues with the source code. You are welcome to modify our eslint settings - maybe that shows something more.
