### ISSUE TITLE
Missing citation styles in docker installation of fiduswriter

### ISSUE THREAD

**Issue by mcuxdk** [fiduswriter/fiduswriter#804]
There only seems to be a single APA citation style in the docker installation of fiduswriter. 
How do I add other citation styles?

**Comment by johanneswilm** [comment]
Hey, the docker images are not maintained by us. Which one are you using? This one: https://hub.docker.com/r/moritzf/fiduswriter ? 

I have added instructions to the WIKI on how to manually add citation styles: https://github.com/fiduswriter/fiduswriter/wiki/Add-a-Citation-Style
