### ISSUE TITLE
docx/odt export unavailable

### ISSUE THREAD

**Issue by ebran** [fiduswriter/fiduswriter#855]
I am currently testing Fidus Writer and it works really well, but ODT/DOCX export is unavailable in the application (only HTML, epub, LaTeX is available in the export menu).

I followed the instructions at https://github.com/fiduswriter/fiduswriter/wiki/Installation-on-Ubuntu-18.04 and did not notice any errors (only the warnings "npm WARN rollup-plugin-terser@4.0.4 requires a peer of rollup@>=0.66.0 <2 but none is installed" and "npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents" which I think are irrelevant).

What could be the cause?

**Comment by johanneswilm** [comment]
For some reason you did not get templates installed. This should normally happen when you run `./manage.py init`. You can also go into the administration interface and see if there are export templates registered there.

**Comment by ebran** [comment]
I'm not sure, but I think it was an outdated npm installation... anyway works after reinstall.
