### ISSUE TITLE
issue in comment for &, <, > symbols

### ISSUE THREAD

**Issue by ArupPatel** [fiduswriter/fiduswriter#880]
![gif](https://user-images.githubusercontent.com/46891042/62935387-9adeda00-bde4-11e9-9d85-31656c67f9d6.gif)

These three are converted(escaped) while rendering thee the comment. I checked it for double escaping, but it was not the reason for it.

**Comment by johanneswilm** [comment]
fixed in diffDOM and fiduswriter/develop
