### ISSUE TITLE
Book plugin bugs

### ISSUE THREAD

**Issue by mrchristian** [fiduswriter/fiduswriter#894]
Hi,

I have a few Book plugin bugs I need to log. I have encountered these bugs on my own install of FW and on the https://www.fiduswriter.com/book/ site.

1. If I edit book 'Basic Info' fields the conet is not saved. I save info, then if I navigate away, then back to book, the details have reverted to an earlier version and my changes are not saved.

2. Chapters - I cannot remove chapters, sort chapters, or edit names of chapters.

Thanks

Simon

**Comment by johanneswilm** [comment]
Resolved and checked to be working in 3.7.2.
