### ISSUE TITLE
Fiduswriter in Safari on ipad

### ISSUE THREAD

**Issue by AndreasZitek** [fiduswriter/fiduswriter#90]
I realized that FW is non completely fitting into the ipad screen in Safari when opening a document, and I cannot scroll down multiple pages, only page 1 is shown. It fits into the screen, when a comment is posted aside of the text, which leads to pushing the right side of FW into the window.

**Comment by johanneswilm** [comment]
The 3.0 branch does support all other browsers now. Please reopen if you find more issues with this, @AndreasZitek .
