### ISSUE TITLE
Cannot Add a new Template

### ISSUE THREAD

**Issue by red-rego** [fiduswriter/fiduswriter#906]
**I tried to add a new template in my admin panel but was unsuccessful.**

![image](https://user-images.githubusercontent.com/52812950/65753786-50fc4a00-e12d-11e9-8869-08cabbd0ea2f.png)

**The error in my browser is as follows :-** 

![image](https://user-images.githubusercontent.com/52812950/65753838-712c0900-e12d-11e9-922f-f42ebc7ab24b.png)

**The error in my terminal :-** 

`ERROR:javascript_error:Got error: 
	context: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36
	details: unhandledrejection, Unknown node type: undefined, RangeError: Unknown node type: undefined
    at Schema.nodeType (webpack:///./node_modules/prosemirror-model/dist/index.js?:2444:23)
    at Function.fromJSON (webpack:///./node_modules/prosemirror-model/dist/index.js?:1394:17)
    at Schema.nodeFromJSON (webpack:///./node_modules/prosemirror-model/dist/index.js?:2432:15)
    at toFullJSON (webpack:///./js/modules/schema/mini_json.js?:67:17)
    at new DocumentTemplateDesigner (webpack:///./js/modules/document_template/designer.js?:70:87)
    at DocumentTemplateAdmin.initDesigner (webpack:///./js/modules/document_template/admin.js?:76:31)
    at eval (webpack:///./js/modules/document_template/admin.js?:68:15)
	user: rego
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: [Django] ERROR (EXTERNAL IP): Got error: \n	context: Mozilla/5.0
 (X11;
 Linux x86_64) AppleWebKit/537.36 (KHTML,
 like Gecko) Chrome/77.0.3865.75 Safari/537.36\n	details: unhandledrejection,
 Unknown node type: undefined,
 RangeError: Unknown node type: undefined\n    at Schema.nodeType
 (webpack:///./node_modules/prosemirror-model/dist/index.js?:2444:23)\n    at
 Function.fromJSON
 (webpack:///./node_modules/prosemirror-model/dist/index.js?:1394:17)\n    at
 Schema.nodeFromJSON
 (webpack:///./node_modules/prosemirror-model/dist/index.js?:2432:15)\n    at
 toFullJSON (webpack:///./js/modules/schema/mini_json.js?:67:17)\n    at new
 DocumentTemplateDesigner
 (webpack:///./js/modules/document_template/designer.js?:70:87)\n    at
 DocumentTemplateAdmin.initDesigner
 (webpack:///./js/modules/document_template/admin.js?:76:31)\n    at eval
 (webpack:///./js/modules/document_template/admin.js?:68:15)\n	user: rego`

**Fiduswriter version :-** 

master branch
release - 3.7.1

But I can confirm that Standard Article template is editable.

**Comment by johanneswilm** [comment]
resolved in 3.7.2
