### ISSUE TITLE
Adding plugins to snap install?

### ISSUE THREAD

**Issue by mrchristian** [fiduswriter/fiduswriter#956]
Hi,

Is it possible to add plugins to the Snap install, like the book plugin?

Thanks

Simon

**Comment by mrchristian** [comment]
Also If we want to use our own MySQL database I take it we could keep that configuration with a snap install?

**Comment by johanneswilm** [comment]
The book plugin is already part of the snap install. All the officials plugins are part of the snap installation and they can be enabled/disabled individually.

You should be able to write your own custom plugin and make it work with the snap installation, but likely that is not a good idea. If you want to use your own mysql database, I am not sure if you can use it with the snap, but it's probably not a good idea. 

Why is it not a good idea? The snap installs auto updates. So there should be no maintenance required on the part of the server owner. The flipside of that is that the system may update suddenly and unless you also update your custom plugin at the same time, the plugin may no longer work. Or we may have some new requirements for thedatabase that an older mysql server no longer can cope with.
