### ISSUE TITLE
book chapter order changes not appearing in PDF

### ISSUE THREAD

**Issue by mrchristian** [fiduswriter/fiduswriter#980]
In the book area if the chapters are reordered and the book is saved the changes are shown in the book management interface but they do no make any changes to the order of chapters in the PDF.

This in Fidus Writer 3.7.9 and has been tested on two FW installs as well as on Fiduswriter.com

If you have a solution to this issue it would be really appreciated.

Thanks  Simon

**Comment by johanneswilm** [comment]
Should be fixed since at least Fidus Writer 3.9.
