### ISSUE TITLE
Duplicate docs on book chapter import

### ISSUE THREAD

**Issue by mrchristian** [fiduswriter/fiduswriter#991]
Hi,

When adding docs to books, the available docs in the add docs to book list get duplicate listings (there are not actually duplicate docs), sometimes 2x copies of a doc, sometimes 10x of a doc.

This does not apply to all docs in the list, just a few.

But it does persist.

I moved over a couple of the duplicating docs to another Fidus Writer 3.7 test install to see if it was the docs causing the problem, but no.

I have not yet replicated the problem on a my test install, but this will be the next step.

Thanks

Simon

**Comment by johanneswilm** [comment]
This should not apply to 3.10.
